import path from 'path';
import { promises as fs } from 'fs';

/**
 * v6 → v7 migration cleanup (docs/analysis/v7-performance/ 4.7).
 *
 * v7 stopped generating a long list of always-on rules, hook scripts, spec
 * documents and retired-subsystem skills. `rulebook update` uses this module
 * to remove the rulebook-OWNED leftovers from existing projects — never
 * touching user-authored files — and to normalize spec filenames to the v7
 * lowercase convention. Pure planning is separated from application so
 * `--dry-run` can print the exact plan without writing anything.
 */

/** Rule files v5/v6 projected into .claude/rules/ that v7 no longer ships. */
const RETIRED_CLAUDE_RULES = [
    'full-task-no-questions',
    'multi-agent-teams',
    'consult-analysis-before-implementing',
    'respect-handoff-trigger',
    'diagnostic-first',
    'fail-twice-escalate',
    'no-shortcuts',
    'git-safety',
    'sequential-editing',
    'research-first',
    'follow-task-sequence',
    'incremental-implementation',
    'task-decomposition',
    'incremental-tests',
    'no-deferred',
    'session-workflow',
    'knowledge-base-usage',
];

/** Hook scripts wired by any v5/v6 release. Always rulebook-owned. */
const RETIRED_HOOK_SCRIPTS = [
    'enforce-pre-tool.sh',
    'enforce-no-deferred.sh',
    'enforce-no-shortcuts.sh',
    'enforce-mcp-for-tasks.sh',
    'enforce-team-for-background-agents.sh',
    'enforce-team-for-background-agents.ps1',
    'check-context-and-handoff.sh',
    'resume-from-handoff.sh',
    'on-compact-reinject.sh',
    'terse-activate.sh',
    'terse-activate.ps1',
    'terse-mode-tracker.sh',
    'terse-mode-tracker.ps1',
    'update-check.sh',
    'update-check.ps1',
];

/** Spec documents v7 no longer generates (retired subsystems + module docs). */
const RETIRED_SPECS = [
    'AGENT_AUTOMATION.md',
    'MULTI_AGENT.md',
    'TOKEN_OPTIMIZATION.md',
    'RULEBOOK_TERSE.md',
    'DAG.md',
    'KNOWLEDGE.md',
    'DECISIONS.md',
    'DOCUMENTATION_RULES.md',
    'VECTORIZER.md',
    'SYNAP.md',
    'CONTEXT7.md',
    'GITHUB_MCP.md',
    'GITHUB.md',
    'PLAYWRIGHT.md',
    'SUPABASE.md',
    'SERENA.md',
    'RULEBOOK_MCP.md',
    'SEQUENTIAL_THINKING.md',
];

/** Skills that existed only to serve retired subsystems. */
const RETIRED_SKILLS = ['rulebook-terse', 'rulebook-terse-commit', 'rulebook-terse-review', 'handoff'];

/**
 * Slash commands retired in phase6 — they duplicated the consolidated MCP
 * tools verb-for-verb (F-004/F-008 in docs/analysis/post-v7-context-optimization).
 */
const RETIRED_COMMANDS = [
    'rulebook-task-create.md',
    'rulebook-task-list.md',
    'rulebook-task-show.md',
    'rulebook-task-archive.md',
    'rulebook-task-apply.md',
    'rulebook-task-validate.md',
    'rulebook-knowledge-add.md',
    'rulebook-knowledge-list.md',
    'rulebook-learn-capture.md',
    'rulebook-learn-list.md',
    'rulebook-decision-create.md',
    'rulebook-decision-list.md',
];

/** Markers proving a command doc was shipped by rulebook. */
const COMMAND_MARKERS = ['<!-- RULEBOOK:START', 'MCP equivalent', 'rulebook_task', 'rulebook_memory'];

/** Loose .rulebook files from retired subsystems. */
const RETIRED_RULEBOOK_FILES = ['COMPACT_CONTEXT.md', '.terse-mode'];

/** Markers proving a file was written by rulebook (any past version). */
const OWNED_MARKERS = ['Generated by @hivehub/rulebook', 'Generated by @hivellm/rulebook'];

export interface V6CleanupPlan {
    /** Files/dirs to delete (rulebook-owned leftovers). Repo-relative. */
    remove: string[];
    /** Retired-name files kept because they look user-authored. */
    preserved: string[];
    /** Uppercase spec files to rename to the v7 lowercase convention. */
    rename: Array<{ from: string; to: string }>;
}

async function exists(p: string): Promise<boolean> {
    return fs.stat(p).then(
        () => true,
        () => false
    );
}

async function isRulebookOwned(filePath: string): Promise<boolean> {
    try {
        const content = await fs.readFile(filePath, 'utf-8');
        return OWNED_MARKERS.some((m) => content.includes(m));
    } catch {
        return false;
    }
}

/** Compute the v6→v7 cleanup plan. Read-only. */
export async function planV6Cleanup(projectRoot: string): Promise<V6CleanupPlan> {
    const plan: V6CleanupPlan = { remove: [], preserved: [], rename: [] };
    const rel = (p: string) => path.relative(projectRoot, p).replace(/\\/g, '/');

    // .claude/rules — retired names, only when rulebook-owned.
    const rulesDir = path.join(projectRoot, '.claude', 'rules');
    for (const name of RETIRED_CLAUDE_RULES) {
        const p = path.join(rulesDir, `${name}.md`);
        if (!(await exists(p))) continue;
        if (await isRulebookOwned(p)) plan.remove.push(rel(p));
        else plan.preserved.push(rel(p));
    }

    // .claude/hooks — retired scripts are always rulebook-owned.
    for (const name of RETIRED_HOOK_SCRIPTS) {
        const p = path.join(projectRoot, '.claude', 'hooks', name);
        if (await exists(p)) plan.remove.push(rel(p));
    }

    // .claude/skills — retired-subsystem skills only.
    for (const name of RETIRED_SKILLS) {
        const p = path.join(projectRoot, '.claude', 'skills', name);
        if (await exists(p)) plan.remove.push(rel(p));
    }

    // .claude/commands — phase6-retired slash commands (rulebook-shipped only).
    for (const name of RETIRED_COMMANDS) {
        const p = path.join(projectRoot, '.claude', 'commands', name);
        if (!(await exists(p))) continue;
        try {
            const content = await fs.readFile(p, 'utf-8');
            if (COMMAND_MARKERS.some((m) => content.includes(m))) plan.remove.push(rel(p));
            else plan.preserved.push(rel(p));
        } catch {
            // unreadable — leave it alone
        }
    }

    // .rulebook/specs — retired docs + uppercase → lowercase normalization.
    const specsDir = path.join(projectRoot, '.rulebook', 'specs');
    if (await exists(specsDir)) {
        const retired = new Set(RETIRED_SPECS);
        for (const entry of await fs.readdir(specsDir)) {
            const p = path.join(specsDir, entry);
            if (retired.has(entry)) {
                plan.remove.push(rel(p));
            } else if (entry !== entry.toLowerCase() && entry.endsWith('.md')) {
                plan.rename.push({ from: rel(p), to: rel(path.join(specsDir, entry.toLowerCase())) });
            }
        }
    }

    // .rulebook/rules — the v5 canonical source dir is fully retired.
    const canonicalDir = path.join(projectRoot, '.rulebook', 'rules');
    if (await exists(canonicalDir)) {
        for (const entry of await fs.readdir(canonicalDir)) {
            const base = entry.replace(/\.md$/, '');
            if (RETIRED_CLAUDE_RULES.includes(base)) {
                plan.remove.push(rel(path.join(canonicalDir, entry)));
            }
        }
    }

    // Loose retired .rulebook files + the handoff directory.
    for (const name of RETIRED_RULEBOOK_FILES) {
        const p = path.join(projectRoot, '.rulebook', name);
        if (await exists(p)) plan.remove.push(rel(p));
    }
    const handoffDir = path.join(projectRoot, '.rulebook', 'handoff');
    if (await exists(handoffDir)) plan.remove.push(rel(handoffDir));

    return plan;
}

/** Apply a cleanup plan. Returns the paths actually removed/renamed. */
export async function applyV6Cleanup(
    projectRoot: string,
    plan: V6CleanupPlan
): Promise<{ removed: string[]; renamed: string[] }> {
    const removed: string[] = [];
    const renamed: string[] = [];

    for (const relPath of plan.remove) {
        const p = path.join(projectRoot, relPath);
        try {
            await fs.rm(p, { recursive: true, force: true });
            removed.push(relPath);
        } catch {
            // best-effort — report only what actually went away
        }
    }

    for (const { from, to } of plan.rename) {
        const src = path.join(projectRoot, from);
        const dst = path.join(projectRoot, to);
        try {
            // Two-step rename survives case-insensitive filesystems.
            const tmp = `${dst}.v7tmp`;
            await fs.rename(src, tmp);
            await fs.rename(tmp, dst);
            renamed.push(`${from} → ${to}`);
        } catch {
            // best-effort
        }
    }

    // Drop .rulebook/rules if the cleanup emptied it.
    const canonicalDir = path.join(projectRoot, '.rulebook', 'rules');
    try {
        const left = await fs.readdir(canonicalDir);
        if (left.length === 0) await fs.rmdir(canonicalDir);
    } catch {
        // absent — fine
    }

    return { removed, renamed };
}
