import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { ToolContext } from './context.js';

export function registerRulesTools(server: McpServer, ctx: ToolContext): void {
    const { projectRoot, workspaceManager, projectIdSchema } = ctx;

    server.registerTool(
        'rulebook_rules_list',
        {
            title: 'List Rules',
            description:
                'List canonical rules from .rulebook/rules/ AND path-scoped language rules from .claude/rules/. Each entry is classified by source (generated by rulebook vs user-authored).',
            inputSchema: {
                projectId: projectIdSchema,
            },
        },
        async (args) => {
            try {
                const root =
                    args.projectId && workspaceManager
                        ? (await workspaceManager.getWorker(args.projectId)).projectRoot
                        : projectRoot;
                const { listRules } = await import('../../core/rule-engine.js');
                const { listRulesWithSource } = await import(
                    '../../core/generators/rules-generator.js'
                );
                const canonical = await listRules(root);
                const languageRules = await listRulesWithSource(root);
                return {
                    content: [
                        {
                            type: 'text',
                            text: JSON.stringify({
                                success: true,
                                canonical,
                                languageRules,
                                count: canonical.length + languageRules.length,
                            }),
                        },
                    ],
                };
            } catch (error) {
                return {
                    content: [
                        {
                            type: 'text',
                            text: JSON.stringify({
                                success: false,
                                error: error instanceof Error ? error.message : String(error),
                            }),
                        },
                    ],
                };
            }
        }
    );
}
