import { describe, it, expect } from 'vitest';
import {
  generateAgentsContent,
  generateFullAgents,
  generateGitRules,
  generateModularAgents,
} from '../src/core/generator';
import type { ProjectConfig } from '../src/types';

describe('generator', () => {
  const baseConfig: ProjectConfig = {
    languages: ['rust'],
    modules: ['vectorizer'],
    ides: ['cursor'],
    projectType: 'application',
    coverageThreshold: 95,
    strictDocs: true,
    generateWorkflows: true,
  };

  describe('generateAgentsContent', () => {
    it('should generate RULEBOOK block with project rules', async () => {
      const content = await generateAgentsContent(baseConfig);

      expect(content).toContain('<!-- RULEBOOK:START -->');
      expect(content).toContain('<!-- RULEBOOK:END -->');
      expect(content).toContain('# Project Rules');
      expect(content).toContain('Documentation Standards');
      expect(content).toContain('Testing Requirements');
      expect(content).toContain('Feature Development Workflow');
    });

    it('should include coverage threshold', async () => {
      const config = { ...baseConfig, coverageThreshold: 85 };
      const content = await generateAgentsContent(config);

      expect(content).toContain('**Minimum Coverage**: 85%');
    });

    it('should include strict documentation rules when enabled', async () => {
      const config = { ...baseConfig, strictDocs: true };
      const content = await generateAgentsContent(config);

      expect(content).toContain('Minimize Markdown files');
      expect(content).toContain('Allowed Root-Level Documentation');
      expect(content).toContain('/docs` directory');
    });

    it('should include .rulesignore documentation', async () => {
      const content = await generateAgentsContent(baseConfig);

      expect(content).toContain('Rules Configuration');
      expect(content).toContain('.rulesignore');
    });

    it('should include generated timestamp', async () => {
      const content = await generateAgentsContent(baseConfig);

      expect(content).toContain('Generated by @hivellm/rulebook');
      expect(content).toMatch(/Generated at: \d{4}-\d{2}-\d{2}T/);
    });
  });

  describe('generateFullAgents', () => {
    it('should generate complete AGENTS.md with all sections (modular mode)', async () => {
      const config: ProjectConfig = {
        languages: ['rust', 'typescript'],
        modules: ['vectorizer', 'synap'],
        ides: ['cursor'],
        projectType: 'application',
        coverageThreshold: 95,
        strictDocs: true,
        generateWorkflows: true,
        modular: true,
      };

      const content = await generateFullAgents(config, '/tmp/test');

      // Should include RULEBOOK block
      expect(content).toContain('<!-- RULEBOOK:START -->');
      expect(content).toContain('<!-- RULEBOOK:END -->');

      // Should include language references (not embedded blocks in modular mode)
      expect(content).toContain('Language-Specific Rules');
      expect(content).toContain('/rulebook/RUST.md');
      expect(content).toContain('/rulebook/TYPESCRIPT.md');

      // Should include module references
      expect(content).toContain('Module-Specific Instructions');
      expect(content).toContain('/rulebook/VECTORIZER.md');
      expect(content).toContain('/rulebook/SYNAP.md');
    });

    it('should generate content for single language (modular mode)', async () => {
      const config = { ...baseConfig, modular: true };
      const content = await generateFullAgents(config, '/tmp/test');

      expect(content).toContain('/rulebook/RUST.md');
      expect(content).not.toContain('/rulebook/TYPESCRIPT.md');
    });

    it('should generate content for multiple modules (modular mode)', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        modules: ['vectorizer', 'synap', 'context7'],
        modular: true,
      };
      const content = await generateFullAgents(config, '/tmp/test');

      expect(content).toContain('/rulebook/VECTORIZER.md');
      expect(content).toContain('/rulebook/SYNAP.md');
      expect(content).toContain('/rulebook/CONTEXT7.md');
    });

    it('should generate embedded content in legacy mode', async () => {
      const config: ProjectConfig = {
        languages: ['rust'],
        modules: ['vectorizer'],
        ides: ['cursor'],
        projectType: 'application',
        coverageThreshold: 95,
        strictDocs: true,
        generateWorkflows: true,
        modular: false, // Explicitly disable modular
      };

      const content = await generateFullAgents(config);

      // Should include embedded blocks in legacy mode
      expect(content).toContain('<!-- RUST:START -->');
      expect(content).toContain('<!-- RUST:END -->');
      expect(content).toContain('<!-- VECTORIZER:START -->');
      expect(content).toContain('<!-- VECTORIZER:END -->');
    });

    it('should include Git workflow when enabled', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: true,
        gitPushMode: 'manual',
      };
      const content = await generateFullAgents(config);

      expect(content).toContain('<!-- GIT:START -->');
      expect(content).toContain('<!-- GIT:END -->');
    });

    it('should exclude Git workflow when disabled', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: false,
      };
      const content = await generateFullAgents(config);

      expect(content).not.toContain('<!-- GIT:START -->');
    });
  });

  describe('generateGitRules', () => {
    it('should generate Git rules with manual push mode', async () => {
      const content = await generateGitRules('manual');

      expect(content).toContain('<!-- GIT:START -->');
      expect(content).toContain('<!-- GIT:END -->');
      expect(content).toContain('MANUAL');
      expect(content).toContain('Never execute `git push` commands automatically');
      expect(content).toContain('MANUAL ACTION REQUIRED');
    });

    it('should generate Git rules with prompt push mode', async () => {
      const content = await generateGitRules('prompt');

      expect(content).toContain('<!-- GIT:START -->');
      expect(content).toContain('PROMPT');
      expect(content).toContain('ask user permission before pushing');
    });

    it('should generate Git rules with auto push mode', async () => {
      const content = await generateGitRules('auto');

      expect(content).toContain('<!-- GIT:START -->');
      expect(content).toContain('AUTO');
      expect(content).toContain('Automatic push enabled');
      expect(content).toContain('SSH key has no password');
    });
  });

  describe('light mode', () => {
    it('should skip quality enforcement in light mode', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        lightMode: true,
      };
      const content = await generateAgentsContent(config);

      expect(content).not.toContain('QUALITY_ENFORCEMENT');
      expect(content).not.toContain('STRICTLY FORBIDDEN');
    });

    it('should include quality enforcement when not in light mode', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        lightMode: false,
      };
      const content = await generateAgentsContent(config);

      expect(content).toContain('Quality Enforcement Rules');
    });
  });

  describe('documentation strictness', () => {
    it('should use relaxed docs when strictDocs is false', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        strictDocs: false,
      };
      const content = await generateAgentsContent(config);

      expect(content).not.toContain('Minimize Markdown files');
      expect(content).toContain('well-organized');
    });
  });

  describe('frameworks and tools', () => {
    it('should include frameworks when specified (modular mode)', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        frameworks: ['nestjs', 'react'],
        modular: true,
      };
      const content = await generateFullAgents(config, '/tmp/test');

      expect(content).toContain('Framework-Specific Rules');
      expect(content).toContain('/rulebook/NESTJS.md');
      expect(content).toContain('/rulebook/REACT.md');
    });

    it('should include CLI tools when specified', () => {
      const config: ProjectConfig = {
        ...baseConfig,
        cliTools: ['aider', 'continue'],
      };
      // Just test that config accepts CLI tools
      expect(config.cliTools).toEqual(['aider', 'continue']);
    });

    it('should handle empty frameworks array', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        frameworks: [],
      };
      const content = await generateFullAgents(config);

      expect(content).not.toContain('<!-- NESTJS:START -->');
      expect(content).not.toContain('<!-- REACT:START -->');
    });

    it('should handle undefined frameworks', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        frameworks: undefined,
      };
      const content = await generateFullAgents(config);

      expect(content).toBeDefined();
      expect(content.length).toBeGreaterThan(0);
    });

    it('should include Git workflow when includeGitWorkflow is true', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: true,
        gitPushMode: 'manual',
      };
      const content = await generateFullAgents(config);

      expect(content).toContain('Git Workflow');
    });

    it('should not include Git workflow when includeGitWorkflow is false', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: false,
      };
      const content = await generateFullAgents(config);

      // Git workflow should not be present
      expect(content).toBeDefined();
    });

    it('should use default gitPushMode when not specified', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: true,
        // gitPushMode not specified
      };
      const content = await generateFullAgents(config);

      expect(content).toContain('Git Workflow');
    });
  });

  describe('generateModularAgents branch coverage', () => {
    it('should handle empty languages array', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        languages: [],
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('<!-- RULEBOOK:START -->');
      expect(content).not.toContain('## Language-Specific Rules');
    });

    it('should handle empty frameworks array', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        frameworks: [],
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('<!-- RULEBOOK:START -->');
      expect(content).not.toContain('## Framework-Specific Rules');
    });

    it('should handle undefined frameworks', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        frameworks: undefined,
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('<!-- RULEBOOK:START -->');
      expect(content).not.toContain('## Framework-Specific Rules');
    });

    it('should handle minimal mode', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        minimal: true,
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('<!-- RULEBOOK:START -->');
      // AGENT_AUTOMATION should not be included in minimal mode
    });

    it('should handle empty modules array', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        modules: [],
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('<!-- RULEBOOK:START -->');
      expect(content).not.toContain('## Module-Specific Instructions');
    });

    it('should include Git workflow when includeGitWorkflow is true', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: true,
        gitPushMode: 'manual',
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('Git Workflow');
    });

    it('should not include Git workflow when includeGitWorkflow is false', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        includeGitWorkflow: false,
        modular: true,
      };
      const content = await generateModularAgents(config, '/tmp/test');

      expect(content).toContain('<!-- RULEBOOK:START -->');
    });

    it('should use custom rulebookDir', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        rulebookDir: 'custom-rulebook',
        modular: true,
      };
      const testDir = '/tmp/test-custom-dir';
      const content = await generateModularAgents(config, testDir);

      expect(content).toContain('/custom-rulebook/');
      // The reference paths should use custom-rulebook
      expect(content).toMatch(/\/custom-rulebook\/[A-Z_]+\.md/);
    });
  });

  describe('generateFullAgents legacy mode', () => {
    it('should use legacy mode when modular is false', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        languages: ['typescript'],
        modular: false, // Explicitly disable modular
      };
      const content = await generateFullAgents(config);

      // Should embed content, not use references
      expect(content).toContain('<!-- TYPESCRIPT:START -->');
      expect(content).not.toContain('/rulebook/');
    });

    it('should handle minimal mode in legacy', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        modular: false,
        minimal: true,
      };
      const content = await generateFullAgents(config);

      expect(content).toBeDefined();
      // AGENT_AUTOMATION should not be included
    });

    it('should handle includeGitWorkflow in legacy mode', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        modular: false,
        includeGitWorkflow: true,
        gitPushMode: 'auto',
      };
      const content = await generateFullAgents(config);

      expect(content).toContain('Git Workflow');
    });
  });

  describe('multiple IDE support', () => {
    it('should accept multiple IDEs in config', () => {
      const config: ProjectConfig = {
        ...baseConfig,
        ides: ['cursor', 'windsurf', 'vscode'],
      };
      // IDEs are used for prompts but not in generated content
      expect(config.ides).toEqual(['cursor', 'windsurf', 'vscode']);
    });
  });

  describe('project types', () => {
    it('should handle library project type', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        projectType: 'library',
      };
      const content = await generateFullAgents(config);

      expect(content).toBeDefined();
      expect(content.length).toBeGreaterThan(0);
    });

    it('should handle CLI project type', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        projectType: 'cli',
      };
      const content = await generateFullAgents(config);

      expect(content).toBeDefined();
      expect(content.length).toBeGreaterThan(0);
    });

    it('should handle monorepo project type', async () => {
      const config: ProjectConfig = {
        ...baseConfig,
        projectType: 'monorepo',
      };
      const content = await generateFullAgents(config);

      expect(content).toBeDefined();
      expect(content.length).toBeGreaterThan(0);
    });
  });
});
