import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { generateGitignoreContent, generateGitignore } from '../src/core/gitignore-generator.js';
import { promises as fs } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import type { LanguageDetection } from '../src/types.js';

describe('Gitignore Generator', () => {
  let testDir: string;

  beforeEach(async () => {
    testDir = join(tmpdir(), `rulebook-gitignore-test-${Date.now()}`);
    await fs.mkdir(testDir, { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(testDir, { recursive: true, force: true });
  });

  describe('generateGitignoreContent', () => {
    it('should generate gitignore for TypeScript', () => {
      const languages: LanguageDetection[] = [{ language: 'typescript', confidence: 100 }];
      const content = generateGitignoreContent(languages);

      expect(content).toContain('# TypeScript');
      expect(content).toContain('node_modules/');
      expect(content).toContain('dist/');
      expect(content).toContain('*.tsbuildinfo');
    });

    it('should generate gitignore for Python', () => {
      const languages: LanguageDetection[] = [{ language: 'python', confidence: 100 }];
      const content = generateGitignoreContent(languages);

      expect(content).toContain('# Python');
      expect(content).toContain('__pycache__/');
      expect(content).toContain('*.py[cod]');
      expect(content).toContain('.venv/');
    });

    it('should generate gitignore for Rust', () => {
      const languages: LanguageDetection[] = [{ language: 'rust', confidence: 100 }];
      const content = generateGitignoreContent(languages);

      expect(content).toContain('# Rust');
      expect(content).toContain('target/');
      expect(content).toContain('Cargo.lock');
    });

    it('should include common patterns', () => {
      const languages: LanguageDetection[] = [{ language: 'typescript', confidence: 100 }];
      const content = generateGitignoreContent(languages);

      expect(content).toContain('.DS_Store');
      expect(content).toContain('.env');
      expect(content).toContain('*.log');
    });

    it('should handle multiple languages', () => {
      const languages: LanguageDetection[] = [
        { language: 'typescript', confidence: 100 },
        { language: 'python', confidence: 80 },
      ];
      const content = generateGitignoreContent(languages);

      expect(content).toContain('# TypeScript');
      expect(content).toContain('# Python');
      expect(content).toContain('node_modules/');
      expect(content).toContain('__pycache__/');
    });

    it('should include header with timestamp', () => {
      const languages: LanguageDetection[] = [{ language: 'typescript', confidence: 100 }];
      const content = generateGitignoreContent(languages);

      expect(content).toContain('# .gitignore');
      expect(content).toContain('# Generated by @hivellm/rulebook');
      expect(content).toContain('# Generated at:');
    });
  });

  describe('generateGitignore', () => {
    it('should create new .gitignore file', async () => {
      const languages: LanguageDetection[] = [{ language: 'typescript', confidence: 100 }];
      const result = await generateGitignore(testDir, languages);

      expect(result.created).toBe(true);
      expect(result.updated).toBe(false);

      const gitignorePath = join(testDir, '.gitignore');
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# TypeScript');
      expect(content).toContain('node_modules/');
    });

    it('should update existing .gitignore with missing patterns', async () => {
      // Create existing .gitignore
      const gitignorePath = join(testDir, '.gitignore');
      await fs.writeFile(gitignorePath, 'node_modules/\n*.log\n');

      const languages: LanguageDetection[] = [{ language: 'typescript', confidence: 100 }];
      const result = await generateGitignore(testDir, languages);

      expect(result.created).toBe(false);
      expect(result.updated).toBe(true);

      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('node_modules/'); // Existing
      expect(content).toContain('# Patterns added by @hivellm/rulebook');
    });

    it('should not update .gitignore if all patterns exist', async () => {
      // Create .gitignore with all patterns
      const languages: LanguageDetection[] = [{ language: 'typescript', confidence: 100 }];
      const fullContent = generateGitignoreContent(languages);
      const gitignorePath = join(testDir, '.gitignore');
      await fs.writeFile(gitignorePath, fullContent);

      const result = await generateGitignore(testDir, languages);

      expect(result.created).toBe(false);
      expect(result.updated).toBe(false);
    });

    it('should handle Go language patterns', async () => {
      const languages: LanguageDetection[] = [{ language: 'go', confidence: 100 }];
      await generateGitignore(testDir, languages);

      const gitignorePath = join(testDir, '.gitignore');
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# Go');
      expect(content).toContain('vendor/');
      expect(content).toContain('*.test');
    });

    it('should handle Java language patterns', async () => {
      const languages: LanguageDetection[] = [{ language: 'java', confidence: 100 }];
      await generateGitignore(testDir, languages);

      const gitignorePath = join(testDir, '.gitignore');
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# Java');
      expect(content).toContain('target/');
      expect(content).toContain('*.class');
    });
  });
});
