import { promises as fs } from 'fs';
import { tmpdir } from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
    hasEmbeddedTemplates,
    hasFlatLayout,
    migrateEmbeddedTemplates,
    migrateFlatToSpecs,
} from '../src/core/migrator';
import type { ExistingAgentsInfo, ProjectConfig } from '../src/types';
import { fileExists, readFile } from '../src/utils/file-system';

describe('migrator', () => {
    // Use unique temp directory per run to avoid EPERM conflicts with parallel workers
    let testDir: string;

    const testAgentsContent = `<!-- RULEBOOK:START -->
# Project Rules
Generated by @hivellm/rulebook
<!-- RULEBOOK:END -->

<!-- TYPESCRIPT:START -->
# TypeScript Rules
TypeScript-specific content here.
<!-- TYPESCRIPT:END -->

<!-- VECTORIZER:START -->
# Vectorizer Instructions
Vectorizer-specific content here.
<!-- VECTORIZER:END -->
`;

    function makeExistingAgents(): ExistingAgentsInfo {
        return {
            exists: true,
            path: path.join(testDir, 'AGENTS.md'),
            content: testAgentsContent,
            blocks: [
                {
                    name: 'RULEBOOK',
                    startLine: 0,
                    endLine: 3,
                    content:
                        '<!-- RULEBOOK:START -->\n# Project Rules\nGenerated by @hivellm/rulebook\n<!-- RULEBOOK:END -->',
                },
                {
                    name: 'TYPESCRIPT',
                    startLine: 5,
                    endLine: 7,
                    content:
                        '<!-- TYPESCRIPT:START -->\n# TypeScript Rules\nTypeScript-specific content here.\n<!-- TYPESCRIPT:END -->',
                },
                {
                    name: 'VECTORIZER',
                    startLine: 9,
                    endLine: 11,
                    content:
                        '<!-- VECTORIZER:START -->\n# Vectorizer Instructions\nVectorizer-specific content here.\n<!-- VECTORIZER:END -->',
                },
            ],
        };
    }

    const config: ProjectConfig = {
        languages: ['typescript'],
        modules: ['vectorizer'],
        ides: ['cursor'],
        projectType: 'application',
        coverageThreshold: 95,
        strictDocs: true,
        generateWorkflows: true,
        modular: true,
    };

    beforeEach(async () => {
        testDir = path.join(
            tmpdir(),
            `rulebook-migrator-test-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
        );
        await fs.mkdir(testDir, { recursive: true });
    });

    afterEach(async () => {
        try {
            await fs.rm(testDir, { recursive: true, force: true });
        } catch {
            // Ignore errors
        }
    });

    describe('hasEmbeddedTemplates', () => {
        it('should detect embedded language templates', () => {
            expect(hasEmbeddedTemplates(makeExistingAgents())).toBe(true);
        });

        it('should detect embedded module templates', () => {
            const moduleAgents: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content:
                    '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->\n<!-- VECTORIZER:START -->\n<!-- VECTORIZER:END -->',
                blocks: [],
            };
            expect(hasEmbeddedTemplates(moduleAgents)).toBe(true);
        });

        it('should return false when content is null', () => {
            const noContent: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content: undefined,
                blocks: [],
            };
            expect(hasEmbeddedTemplates(noContent)).toBe(false);
        });

        it('should return false for modular structure', () => {
            const modularAgents: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content:
                    '<!-- RULEBOOK:START -->\n# Project Rules\n<!-- RULEBOOK:END -->\n\nSee /rulebook/TYPESCRIPT.md',
                blocks: [
                    {
                        name: 'RULEBOOK',
                        startLine: 0,
                        endLine: 2,
                        content: '<!-- RULEBOOK:START -->\n# Project Rules\n<!-- RULEBOOK:END -->',
                    },
                ],
            };
            expect(hasEmbeddedTemplates(modularAgents)).toBe(false);
        });

        it('should return false for empty content', () => {
            const emptyAgents: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content: '',
                blocks: [],
            };
            expect(hasEmbeddedTemplates(emptyAgents)).toBe(false);
        });
    });

    describe('migrateEmbeddedTemplates', () => {
        it('should extract templates to /rulebook/ directory', async () => {
            const result = await migrateEmbeddedTemplates(makeExistingAgents(), config, testDir);

            expect(result.extractedLanguages).toContain('typescript');
            expect(result.extractedModules).toContain('vectorizer');

            // Verify files were created
            const typescriptPath = path.join(testDir, '.rulebook', 'specs', 'TYPESCRIPT.md');
            const vectorizerPath = path.join(testDir, '.rulebook', 'specs', 'VECTORIZER.md');

            expect(await fileExists(typescriptPath)).toBe(true);
            expect(await fileExists(vectorizerPath)).toBe(true);

            // Verify content
            const typescriptContent = await readFile(typescriptPath);
            expect(typescriptContent).toContain('TypeScript Rules');
            expect(typescriptContent).toContain('<!-- TYPESCRIPT:START -->');

            const vectorizerContent = await readFile(vectorizerPath);
            expect(vectorizerContent).toContain('Vectorizer Instructions');
            expect(vectorizerContent).toContain('<!-- VECTORIZER:START -->');
        });

        it('should handle empty content', async () => {
            const emptyAgents: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content: undefined,
                blocks: [],
            };

            const result = await migrateEmbeddedTemplates(emptyAgents, config, testDir);

            expect(result.extractedLanguages).toEqual([]);
            expect(result.extractedModules).toEqual([]);
        });

        it('should generate new templates when blocks not found', async () => {
            const agentsWithoutBlocks: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
                blocks: [
                    {
                        name: 'RULEBOOK',
                        startLine: 0,
                        endLine: 1,
                        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
                    },
                ],
            };

            const result = await migrateEmbeddedTemplates(agentsWithoutBlocks, config, testDir);

            expect(result.extractedLanguages).toContain('typescript');
            expect(result.extractedModules).toContain('vectorizer');

            // Verify files were created (generated, not extracted)
            const typescriptPath = path.join(testDir, '.rulebook', 'specs', 'TYPESCRIPT.md');
            const vectorizerPath = path.join(testDir, '.rulebook', 'specs', 'VECTORIZER.md');

            expect(await fileExists(typescriptPath)).toBe(true);
            expect(await fileExists(vectorizerPath)).toBe(true);
        });

        it('should handle language blocks without content', async () => {
            const agentsWithEmptyBlock: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
                blocks: [
                    {
                        name: 'RULEBOOK',
                        startLine: 0,
                        endLine: 1,
                        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
                    },
                    {
                        name: 'TYPESCRIPT',
                        startLine: 2,
                        endLine: 2,
                        content: '', // Empty content
                    },
                ],
            };

            const result = await migrateEmbeddedTemplates(agentsWithEmptyBlock, config, testDir);

            // Should generate new template when block has no content
            expect(result.extractedLanguages).toContain('typescript');
            const typescriptPath = path.join(testDir, '.rulebook', 'specs', 'TYPESCRIPT.md');
            expect(await fileExists(typescriptPath)).toBe(true);
        });

        it('should handle multiple languages and modules', async () => {
            const multiConfig: ProjectConfig = {
                languages: ['typescript', 'rust'],
                modules: ['vectorizer', 'synap'],
                ides: ['cursor'],
                projectType: 'application',
                coverageThreshold: 95,
                strictDocs: true,
                generateWorkflows: true,
                modular: true,
            };

            const multiAgents: ExistingAgentsInfo = {
                exists: true,
                path: '',
                content: `<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->
<!-- TYPESCRIPT:START -->\nTS content\n<!-- TYPESCRIPT:END -->
<!-- RUST:START -->\nRust content\n<!-- RUST:END -->
<!-- VECTORIZER:START -->\nVectorizer content\n<!-- VECTORIZER:END -->
<!-- SYNAP:START -->\nSynap content\n<!-- SYNAP:END -->`,
                blocks: [
                    {
                        name: 'RULEBOOK',
                        startLine: 0,
                        endLine: 1,
                        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
                    },
                    {
                        name: 'TYPESCRIPT',
                        startLine: 2,
                        endLine: 4,
                        content: '<!-- TYPESCRIPT:START -->\nTS content\n<!-- TYPESCRIPT:END -->',
                    },
                    {
                        name: 'RUST',
                        startLine: 5,
                        endLine: 7,
                        content: '<!-- RUST:START -->\nRust content\n<!-- RUST:END -->',
                    },
                    {
                        name: 'VECTORIZER',
                        startLine: 8,
                        endLine: 10,
                        content:
                            '<!-- VECTORIZER:START -->\nVectorizer content\n<!-- VECTORIZER:END -->',
                    },
                    {
                        name: 'SYNAP',
                        startLine: 11,
                        endLine: 13,
                        content: '<!-- SYNAP:START -->\nSynap content\n<!-- SYNAP:END -->',
                    },
                ],
            };

            const result = await migrateEmbeddedTemplates(multiAgents, multiConfig, testDir);

            expect(result.extractedLanguages).toHaveLength(2);
            expect(result.extractedLanguages).toContain('typescript');
            expect(result.extractedLanguages).toContain('rust');
            expect(result.extractedModules).toHaveLength(2);
            expect(result.extractedModules).toContain('vectorizer');
            expect(result.extractedModules).toContain('synap');
        });
    });

    describe('replaceEmbeddedWithReferences', () => {
        it('should generate modular agents content', async () => {
            const { replaceEmbeddedWithReferences } = await import('../src/core/migrator');
            const result = await replaceEmbeddedWithReferences(config, testDir);

            expect(result).toContain('<!-- RULEBOOK:START -->');
            expect(result).toContain('/.rulebook/specs/TYPESCRIPT.md');
            expect(result).not.toContain('/.rulebook/specs/VECTORIZER.md');
        });
    });

    describe('hasFlatLayout', () => {
        it('should return true when known spec files exist in rulebook root but not in specs/', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            await fs.mkdir(rulebookRoot, { recursive: true });
            // Write a known spec file directly in rulebook root (flat layout)
            await fs.writeFile(path.join(rulebookRoot, 'RULEBOOK.md'), '# Rulebook');

            const result = await hasFlatLayout(testDir);
            expect(result).toBe(true);
        });

        it('should return false when specs/ already has the file', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            const specsDir = path.join(rulebookRoot, 'specs');
            await fs.mkdir(specsDir, { recursive: true });
            // Write the file in BOTH locations — specs/ takes precedence
            await fs.writeFile(path.join(rulebookRoot, 'RULEBOOK.md'), '# Rulebook');
            await fs.writeFile(path.join(specsDir, 'RULEBOOK.md'), '# Rulebook');

            const result = await hasFlatLayout(testDir);
            expect(result).toBe(false);
        });

        it('should return false when no known spec files exist in rulebook root', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            await fs.mkdir(rulebookRoot, { recursive: true });
            // Rulebook root is empty — no flat layout files

            const result = await hasFlatLayout(testDir);
            expect(result).toBe(false);
        });
    });

    describe('migrateFlatToSpecs', () => {
        it('should move .md files from rulebook root to specs/ subdirectory', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            await fs.mkdir(rulebookRoot, { recursive: true });
            await fs.writeFile(path.join(rulebookRoot, 'TYPESCRIPT.md'), '# TypeScript rules');
            await fs.writeFile(path.join(rulebookRoot, 'RULEBOOK.md'), '# Rulebook rules');

            const result = await migrateFlatToSpecs(testDir);

            expect(result.migratedFiles).toContain('TYPESCRIPT.md');
            expect(result.migratedFiles).toContain('RULEBOOK.md');

            // Files should now be in specs/
            const tsSpec = path.join(rulebookRoot, 'specs', 'TYPESCRIPT.md');
            const rbSpec = path.join(rulebookRoot, 'specs', 'RULEBOOK.md');
            expect(await fileExists(tsSpec)).toBe(true);
            expect(await fileExists(rbSpec)).toBe(true);

            // Original files should be gone
            expect(await fileExists(path.join(rulebookRoot, 'TYPESCRIPT.md'))).toBe(false);
            expect(await fileExists(path.join(rulebookRoot, 'RULEBOOK.md'))).toBe(false);
        });

        it('should not move non-.md files', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            await fs.mkdir(rulebookRoot, { recursive: true });
            await fs.writeFile(path.join(rulebookRoot, 'config.json'), '{}');
            await fs.writeFile(path.join(rulebookRoot, 'TYPESCRIPT.md'), '# TS');

            const result = await migrateFlatToSpecs(testDir);

            expect(result.migratedFiles).toContain('TYPESCRIPT.md');
            expect(result.migratedFiles).not.toContain('config.json');

            // config.json should still be in root
            const configExists = await fileExists(path.join(rulebookRoot, 'config.json'));
            expect(configExists).toBe(true);
        });

        it('should return empty migratedFiles when rulebook directory does not exist', async () => {
            // testDir/.rulebook does not exist
            const result = await migrateFlatToSpecs(testDir);
            expect(result.migratedFiles).toEqual([]);
        });

        it('should not move subdirectories even if they could match .md pattern', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            const tasksDir = path.join(rulebookRoot, 'tasks');
            await fs.mkdir(tasksDir, { recursive: true });
            await fs.writeFile(path.join(rulebookRoot, 'QUALITY_ENFORCEMENT.md'), '# QE');

            const result = await migrateFlatToSpecs(testDir);

            expect(result.migratedFiles).toContain('QUALITY_ENFORCEMENT.md');
            // tasks directory should still exist
            const tasksDirExists = await fileExists(tasksDir);
            expect(tasksDirExists).toBe(true);
        });

        it('should skip entries that are directories even with .md extension (stat covers line 206)', async () => {
            const rulebookRoot = path.join(testDir, '.rulebook');
            // Create a directory whose name ends in .md to hit the stat.isFile() false branch
            const fakeMdDir = path.join(rulebookRoot, 'fake.md');
            await fs.mkdir(fakeMdDir, { recursive: true });
            await fs.writeFile(path.join(rulebookRoot, 'REAL.md'), '# Real');

            const result = await migrateFlatToSpecs(testDir);

            // Only the real file should be migrated, not the directory
            expect(result.migratedFiles).toContain('REAL.md');
            expect(result.migratedFiles).not.toContain('fake.md');
        });
    });
});
