import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  hasEmbeddedTemplates,
  migrateEmbeddedTemplates,
  hasFlatLayout,
  migrateFlatToSpecs,
} from '../src/core/migrator';
import type { ExistingAgentsInfo, ProjectConfig } from '../src/types';
import { readFile, fileExists } from '../src/utils/file-system';
import path from 'path';
import { promises as fs } from 'fs';

describe('migrator', () => {
  const testDir = path.join(process.cwd(), 'tmp-test-migrator');
  const testAgentsContent = `<!-- RULEBOOK:START -->
# Project Rules
Generated by @hivellm/rulebook
<!-- RULEBOOK:END -->

<!-- TYPESCRIPT:START -->
# TypeScript Rules
TypeScript-specific content here.
<!-- TYPESCRIPT:END -->

<!-- VECTORIZER:START -->
# Vectorizer Instructions
Vectorizer-specific content here.
<!-- VECTORIZER:END -->
`;

  const existingAgents: ExistingAgentsInfo = {
    exists: true,
    path: path.join(testDir, 'AGENTS.md'),
    content: testAgentsContent,
    blocks: [
      {
        name: 'RULEBOOK',
        startLine: 0,
        endLine: 3,
        content:
          '<!-- RULEBOOK:START -->\n# Project Rules\nGenerated by @hivellm/rulebook\n<!-- RULEBOOK:END -->',
      },
      {
        name: 'TYPESCRIPT',
        startLine: 5,
        endLine: 7,
        content:
          '<!-- TYPESCRIPT:START -->\n# TypeScript Rules\nTypeScript-specific content here.\n<!-- TYPESCRIPT:END -->',
      },
      {
        name: 'VECTORIZER',
        startLine: 9,
        endLine: 11,
        content:
          '<!-- VECTORIZER:START -->\n# Vectorizer Instructions\nVectorizer-specific content here.\n<!-- VECTORIZER:END -->',
      },
    ],
  };

  const config: ProjectConfig = {
    languages: ['typescript'],
    modules: ['vectorizer'],
    ides: ['cursor'],
    projectType: 'application',
    coverageThreshold: 95,
    strictDocs: true,
    generateWorkflows: true,
    modular: true,
  };

  beforeEach(async () => {
    await fs.mkdir(testDir, { recursive: true });
  });

  afterEach(async () => {
    try {
      await fs.rm(testDir, { recursive: true, force: true });
    } catch {
      // Ignore errors
    }
  });

  describe('hasEmbeddedTemplates', () => {
    it('should detect embedded language templates', () => {
      expect(hasEmbeddedTemplates(existingAgents)).toBe(true);
    });

    it('should detect embedded module templates', () => {
      const moduleAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content:
          '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->\n<!-- VECTORIZER:START -->\n<!-- VECTORIZER:END -->',
        blocks: [],
      };
      expect(hasEmbeddedTemplates(moduleAgents)).toBe(true);
    });

    it('should detect embedded framework templates', () => {
      const frameworkAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content:
          '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->\n<!-- REACT:START -->\n<!-- REACT:END -->',
        blocks: [],
      };
      expect(hasEmbeddedTemplates(frameworkAgents)).toBe(true);
    });

    it('should return false when content is null', () => {
      const noContent: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: undefined,
        blocks: [],
      };
      expect(hasEmbeddedTemplates(noContent)).toBe(false);
    });

    it('should return false for modular structure', () => {
      const modularAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content:
          '<!-- RULEBOOK:START -->\n# Project Rules\n<!-- RULEBOOK:END -->\n\nSee /rulebook/TYPESCRIPT.md',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 2,
            content: '<!-- RULEBOOK:START -->\n# Project Rules\n<!-- RULEBOOK:END -->',
          },
        ],
      };
      expect(hasEmbeddedTemplates(modularAgents)).toBe(false);
    });

    it('should return false for empty content', () => {
      const emptyAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '',
        blocks: [],
      };
      expect(hasEmbeddedTemplates(emptyAgents)).toBe(false);
    });
  });

  describe('migrateEmbeddedTemplates', () => {
    it('should extract templates to /rulebook/ directory', async () => {
      const result = await migrateEmbeddedTemplates(existingAgents, config, testDir);

      expect(result.extractedLanguages).toContain('typescript');
      expect(result.extractedModules).toContain('vectorizer');

      // Verify files were created
      const typescriptPath = path.join(testDir, '.rulebook', 'specs', 'TYPESCRIPT.md');
      const vectorizerPath = path.join(testDir, '.rulebook', 'specs', 'VECTORIZER.md');

      expect(await fileExists(typescriptPath)).toBe(true);
      expect(await fileExists(vectorizerPath)).toBe(true);

      // Verify content
      const typescriptContent = await readFile(typescriptPath);
      expect(typescriptContent).toContain('TypeScript Rules');
      expect(typescriptContent).toContain('<!-- TYPESCRIPT:START -->');

      const vectorizerContent = await readFile(vectorizerPath);
      expect(vectorizerContent).toContain('Vectorizer Instructions');
      expect(vectorizerContent).toContain('<!-- VECTORIZER:START -->');
    });

    it('should handle empty content', async () => {
      const emptyAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: undefined,
        blocks: [],
      };

      const result = await migrateEmbeddedTemplates(emptyAgents, config, testDir);

      expect(result.extractedLanguages).toEqual([]);
      expect(result.extractedModules).toEqual([]);
      expect(result.extractedFrameworks).toEqual([]);
    });

    it('should generate new templates when blocks not found', async () => {
      const agentsWithoutBlocks: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
        ],
      };

      const result = await migrateEmbeddedTemplates(agentsWithoutBlocks, config, testDir);

      expect(result.extractedLanguages).toContain('typescript');
      expect(result.extractedModules).toContain('vectorizer');

      // Verify files were created (generated, not extracted)
      const typescriptPath = path.join(testDir, '.rulebook', 'specs', 'TYPESCRIPT.md');
      const vectorizerPath = path.join(testDir, '.rulebook', 'specs', 'VECTORIZER.md');

      expect(await fileExists(typescriptPath)).toBe(true);
      expect(await fileExists(vectorizerPath)).toBe(true);
    });

    it('should handle custom rulebookDir', async () => {
      const customConfig: ProjectConfig = {
        ...config,
        rulebookDir: 'custom-rulebook',
      };

      await migrateEmbeddedTemplates(existingAgents, customConfig, testDir);

      const typescriptPath = path.join(testDir, 'custom-rulebook', 'specs', 'TYPESCRIPT.md');
      expect(await fileExists(typescriptPath)).toBe(true);
    });

    it('should extract framework templates', async () => {
      const frameworkAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: `<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->
<!-- REACT:START -->
# React Rules
React content here.
<!-- REACT:END -->`,
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'REACT',
            startLine: 2,
            endLine: 5,
            content: '<!-- REACT:START -->\n# React Rules\nReact content here.\n<!-- REACT:END -->',
          },
        ],
      };

      const frameworkConfig: ProjectConfig = {
        ...config,
        frameworks: ['react'],
      };

      const result = await migrateEmbeddedTemplates(frameworkAgents, frameworkConfig, testDir);

      expect(result.extractedFrameworks).toContain('react');

      const reactPath = path.join(testDir, '.rulebook', 'specs', 'REACT.md');
      expect(await fileExists(reactPath)).toBe(true);

      const reactContent = await readFile(reactPath);
      expect(reactContent).toContain('React Rules');
    });

    it('should handle language blocks without content', async () => {
      const agentsWithEmptyBlock: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'TYPESCRIPT',
            startLine: 2,
            endLine: 2,
            content: '', // Empty content
          },
        ],
      };

      const result = await migrateEmbeddedTemplates(agentsWithEmptyBlock, config, testDir);

      // Should generate new template when block has no content
      expect(result.extractedLanguages).toContain('typescript');
      const typescriptPath = path.join(testDir, '.rulebook', 'specs', 'TYPESCRIPT.md');
      expect(await fileExists(typescriptPath)).toBe(true);
    });

    it('should handle frameworks undefined', async () => {
      const configWithoutFrameworks: ProjectConfig = {
        ...config,
        frameworks: undefined,
      };

      const result = await migrateEmbeddedTemplates(
        existingAgents,
        configWithoutFrameworks,
        testDir
      );

      expect(result.extractedFrameworks).toEqual([]);
    });

    it('should handle multiple languages and modules', async () => {
      const multiConfig: ProjectConfig = {
        languages: ['typescript', 'rust'],
        modules: ['vectorizer', 'synap'],
        ides: ['cursor'],
        projectType: 'application',
        coverageThreshold: 95,
        strictDocs: true,
        generateWorkflows: true,
        modular: true,
      };

      const multiAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: `<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->
<!-- TYPESCRIPT:START -->\nTS content\n<!-- TYPESCRIPT:END -->
<!-- RUST:START -->\nRust content\n<!-- RUST:END -->
<!-- VECTORIZER:START -->\nVectorizer content\n<!-- VECTORIZER:END -->
<!-- SYNAP:START -->\nSynap content\n<!-- SYNAP:END -->`,
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'TYPESCRIPT',
            startLine: 2,
            endLine: 4,
            content: '<!-- TYPESCRIPT:START -->\nTS content\n<!-- TYPESCRIPT:END -->',
          },
          {
            name: 'RUST',
            startLine: 5,
            endLine: 7,
            content: '<!-- RUST:START -->\nRust content\n<!-- RUST:END -->',
          },
          {
            name: 'VECTORIZER',
            startLine: 8,
            endLine: 10,
            content: '<!-- VECTORIZER:START -->\nVectorizer content\n<!-- VECTORIZER:END -->',
          },
          {
            name: 'SYNAP',
            startLine: 11,
            endLine: 13,
            content: '<!-- SYNAP:START -->\nSynap content\n<!-- SYNAP:END -->',
          },
        ],
      };

      const result = await migrateEmbeddedTemplates(multiAgents, multiConfig, testDir);

      expect(result.extractedLanguages).toHaveLength(2);
      expect(result.extractedLanguages).toContain('typescript');
      expect(result.extractedLanguages).toContain('rust');
      expect(result.extractedModules).toHaveLength(2);
      expect(result.extractedModules).toContain('vectorizer');
      expect(result.extractedModules).toContain('synap');
    });
  });

  describe('replaceEmbeddedWithReferences', () => {
    it('should generate modular agents content', async () => {
      const { replaceEmbeddedWithReferences } = await import('../src/core/migrator');
      const result = await replaceEmbeddedWithReferences(config, testDir);

      expect(result).toContain('<!-- RULEBOOK:START -->');
      expect(result).toContain('/.rulebook/specs/TYPESCRIPT.md');
      expect(result).toContain('/.rulebook/specs/VECTORIZER.md');
    });
  });

  describe('migrateEmbeddedTemplates — framework block not found (lines 115-118)', () => {
    it('should generate new framework template when block is not found in existing blocks', async () => {
      const agentsWithoutFrameworkBlock: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          // No REACT block present
        ],
      };

      const frameworkConfig: ProjectConfig = {
        ...config,
        frameworks: ['react'],
      };

      const result = await migrateEmbeddedTemplates(
        agentsWithoutFrameworkBlock,
        frameworkConfig,
        testDir
      );

      expect(result.extractedFrameworks).toContain('react');
      const reactPath = path.join(testDir, '.rulebook', 'specs', 'REACT.md');
      expect(await fileExists(reactPath)).toBe(true);
    });

    it('should generate new framework template when framework block has empty content', async () => {
      const agentsWithEmptyFrameworkBlock: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'NESTJS',
            startLine: 2,
            endLine: 2,
            content: '', // empty content triggers fallback to generateFrameworkRules
          },
        ],
      };

      const frameworkConfig: ProjectConfig = {
        ...config,
        frameworks: ['nestjs'],
      };

      const result = await migrateEmbeddedTemplates(
        agentsWithEmptyFrameworkBlock,
        frameworkConfig,
        testDir
      );

      expect(result.extractedFrameworks).toContain('nestjs');
      const nestjsPath = path.join(testDir, '.rulebook', 'specs', 'NESTJS.md');
      expect(await fileExists(nestjsPath)).toBe(true);
    });

    it('should handle multiple frameworks where some blocks are found and some are not', async () => {
      const agentsMixed: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'REACT',
            startLine: 2,
            endLine: 4,
            content:
              '<!-- REACT:START -->\n# React Rules\nReact content here.\n<!-- REACT:END -->',
          },
          // No VUE block — will trigger generateFrameworkRules
        ],
      };

      const frameworkConfig: ProjectConfig = {
        ...config,
        frameworks: ['react', 'vue'],
      };

      const result = await migrateEmbeddedTemplates(agentsMixed, frameworkConfig, testDir);

      expect(result.extractedFrameworks).toContain('react');
      expect(result.extractedFrameworks).toContain('vue');

      const reactPath = path.join(testDir, '.rulebook', 'specs', 'REACT.md');
      const vuePath = path.join(testDir, '.rulebook', 'specs', 'VUE.md');
      expect(await fileExists(reactPath)).toBe(true);
      expect(await fileExists(vuePath)).toBe(true);
    });
  });

  describe('hasFlatLayout', () => {
    it('should return true when known spec files exist in rulebook root but not in specs/', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      await fs.mkdir(rulebookRoot, { recursive: true });
      // Write a known spec file directly in rulebook root (flat layout)
      await fs.writeFile(path.join(rulebookRoot, 'RULEBOOK.md'), '# Rulebook');

      const result = await hasFlatLayout(testDir);
      expect(result).toBe(true);
    });

    it('should return false when specs/ already has the file', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      const specsDir = path.join(rulebookRoot, 'specs');
      await fs.mkdir(specsDir, { recursive: true });
      // Write the file in BOTH locations — specs/ takes precedence
      await fs.writeFile(path.join(rulebookRoot, 'RULEBOOK.md'), '# Rulebook');
      await fs.writeFile(path.join(specsDir, 'RULEBOOK.md'), '# Rulebook');

      const result = await hasFlatLayout(testDir);
      expect(result).toBe(false);
    });

    it('should return false when no known spec files exist in rulebook root', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      await fs.mkdir(rulebookRoot, { recursive: true });
      // Rulebook root is empty — no flat layout files

      const result = await hasFlatLayout(testDir);
      expect(result).toBe(false);
    });
  });

  describe('migrateFlatToSpecs', () => {
    it('should move .md files from rulebook root to specs/ subdirectory', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      await fs.mkdir(rulebookRoot, { recursive: true });
      await fs.writeFile(path.join(rulebookRoot, 'TYPESCRIPT.md'), '# TypeScript rules');
      await fs.writeFile(path.join(rulebookRoot, 'RULEBOOK.md'), '# Rulebook rules');

      const result = await migrateFlatToSpecs(testDir);

      expect(result.migratedFiles).toContain('TYPESCRIPT.md');
      expect(result.migratedFiles).toContain('RULEBOOK.md');

      // Files should now be in specs/
      const tsSpec = path.join(rulebookRoot, 'specs', 'TYPESCRIPT.md');
      const rbSpec = path.join(rulebookRoot, 'specs', 'RULEBOOK.md');
      expect(await fileExists(tsSpec)).toBe(true);
      expect(await fileExists(rbSpec)).toBe(true);

      // Original files should be gone
      expect(await fileExists(path.join(rulebookRoot, 'TYPESCRIPT.md'))).toBe(false);
      expect(await fileExists(path.join(rulebookRoot, 'RULEBOOK.md'))).toBe(false);
    });

    it('should not move non-.md files', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      await fs.mkdir(rulebookRoot, { recursive: true });
      await fs.writeFile(path.join(rulebookRoot, 'config.json'), '{}');
      await fs.writeFile(path.join(rulebookRoot, 'TYPESCRIPT.md'), '# TS');

      const result = await migrateFlatToSpecs(testDir);

      expect(result.migratedFiles).toContain('TYPESCRIPT.md');
      expect(result.migratedFiles).not.toContain('config.json');

      // config.json should still be in root
      const configExists = await fileExists(path.join(rulebookRoot, 'config.json'));
      expect(configExists).toBe(true);
    });

    it('should return empty migratedFiles when rulebook directory does not exist', async () => {
      // testDir/.rulebook does not exist
      const result = await migrateFlatToSpecs(testDir);
      expect(result.migratedFiles).toEqual([]);
    });

    it('should use custom rulebookDir when provided', async () => {
      const customRoot = path.join(testDir, 'custom-rulebook');
      await fs.mkdir(customRoot, { recursive: true });
      await fs.writeFile(path.join(customRoot, 'GIT.md'), '# Git rules');

      const result = await migrateFlatToSpecs(testDir, 'custom-rulebook');

      expect(result.migratedFiles).toContain('GIT.md');
      const gitSpec = path.join(customRoot, 'specs', 'GIT.md');
      expect(await fileExists(gitSpec)).toBe(true);
    });

    it('should not move subdirectories even if they could match .md pattern', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      const tasksDir = path.join(rulebookRoot, 'tasks');
      await fs.mkdir(tasksDir, { recursive: true });
      await fs.writeFile(path.join(rulebookRoot, 'QUALITY_ENFORCEMENT.md'), '# QE');

      const result = await migrateFlatToSpecs(testDir);

      expect(result.migratedFiles).toContain('QUALITY_ENFORCEMENT.md');
      // tasks directory should still exist
      const tasksDirExists = await fileExists(tasksDir);
      expect(tasksDirExists).toBe(true);
    });

    it('should skip entries that are directories even with .md extension (stat covers line 206)', async () => {
      const rulebookRoot = path.join(testDir, '.rulebook');
      // Create a directory whose name ends in .md to hit the stat.isFile() false branch
      const fakeMdDir = path.join(rulebookRoot, 'fake.md');
      await fs.mkdir(fakeMdDir, { recursive: true });
      await fs.writeFile(path.join(rulebookRoot, 'REAL.md'), '# Real');

      const result = await migrateFlatToSpecs(testDir);

      // Only the real file should be migrated, not the directory
      expect(result.migratedFiles).toContain('REAL.md');
      expect(result.migratedFiles).not.toContain('fake.md');
    });
  });
});
