import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { hasEmbeddedTemplates, migrateEmbeddedTemplates } from '../src/core/migrator';
import type { ExistingAgentsInfo, ProjectConfig } from '../src/types';
import { readFile, fileExists } from '../src/utils/file-system';
import path from 'path';
import { promises as fs } from 'fs';

describe('migrator', () => {
  const testDir = path.join(process.cwd(), 'tmp-test-migrator');
  const testAgentsContent = `<!-- RULEBOOK:START -->
# Project Rules
Generated by @hivellm/rulebook
<!-- RULEBOOK:END -->

<!-- TYPESCRIPT:START -->
# TypeScript Rules
TypeScript-specific content here.
<!-- TYPESCRIPT:END -->

<!-- OPENSPEC:START -->
# OpenSpec Instructions
OpenSpec-specific content here.
<!-- OPENSPEC:END -->
`;

  const existingAgents: ExistingAgentsInfo = {
    exists: true,
    path: path.join(testDir, 'AGENTS.md'),
    content: testAgentsContent,
    blocks: [
      {
        name: 'RULEBOOK',
        startLine: 0,
        endLine: 3,
        content:
          '<!-- RULEBOOK:START -->\n# Project Rules\nGenerated by @hivellm/rulebook\n<!-- RULEBOOK:END -->',
      },
      {
        name: 'TYPESCRIPT',
        startLine: 5,
        endLine: 7,
        content:
          '<!-- TYPESCRIPT:START -->\n# TypeScript Rules\nTypeScript-specific content here.\n<!-- TYPESCRIPT:END -->',
      },
      {
        name: 'OPENSPEC',
        startLine: 9,
        endLine: 11,
        content:
          '<!-- OPENSPEC:START -->\n# OpenSpec Instructions\nOpenSpec-specific content here.\n<!-- OPENSPEC:END -->',
      },
    ],
  };

  const config: ProjectConfig = {
    languages: ['typescript'],
    modules: ['openspec'],
    ides: ['cursor'],
    projectType: 'application',
    coverageThreshold: 95,
    strictDocs: true,
    generateWorkflows: true,
    modular: true,
  };

  beforeEach(async () => {
    await fs.mkdir(testDir, { recursive: true });
  });

  afterEach(async () => {
    try {
      await fs.rm(testDir, { recursive: true, force: true });
    } catch {
      // Ignore errors
    }
  });

  describe('hasEmbeddedTemplates', () => {
    it('should detect embedded language templates', () => {
      expect(hasEmbeddedTemplates(existingAgents)).toBe(true);
    });

    it('should detect embedded module templates', () => {
      const moduleAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content:
          '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->\n<!-- OPENSPEC:START -->\n<!-- OPENSPEC:END -->',
        blocks: [],
      };
      expect(hasEmbeddedTemplates(moduleAgents)).toBe(true);
    });

    it('should detect embedded framework templates', () => {
      const frameworkAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content:
          '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->\n<!-- REACT:START -->\n<!-- REACT:END -->',
        blocks: [],
      };
      expect(hasEmbeddedTemplates(frameworkAgents)).toBe(true);
    });

    it('should return false when content is null', () => {
      const noContent: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: undefined,
        blocks: [],
      };
      expect(hasEmbeddedTemplates(noContent)).toBe(false);
    });

    it('should return false for modular structure', () => {
      const modularAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content:
          '<!-- RULEBOOK:START -->\n# Project Rules\n<!-- RULEBOOK:END -->\n\nSee /rulebook/TYPESCRIPT.md',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 2,
            content: '<!-- RULEBOOK:START -->\n# Project Rules\n<!-- RULEBOOK:END -->',
          },
        ],
      };
      expect(hasEmbeddedTemplates(modularAgents)).toBe(false);
    });

    it('should return false for empty content', () => {
      const emptyAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '',
        blocks: [],
      };
      expect(hasEmbeddedTemplates(emptyAgents)).toBe(false);
    });
  });

  describe('migrateEmbeddedTemplates', () => {
    it('should extract templates to /rulebook/ directory', async () => {
      const result = await migrateEmbeddedTemplates(existingAgents, config, testDir);

      expect(result.extractedLanguages).toContain('typescript');
      expect(result.extractedModules).toContain('openspec');

      // Verify files were created
      const typescriptPath = path.join(testDir, 'rulebook', 'TYPESCRIPT.md');
      const openspecPath = path.join(testDir, 'rulebook', 'OPENSPEC.md');

      expect(await fileExists(typescriptPath)).toBe(true);
      expect(await fileExists(openspecPath)).toBe(true);

      // Verify content
      const typescriptContent = await readFile(typescriptPath);
      expect(typescriptContent).toContain('TypeScript Rules');
      expect(typescriptContent).toContain('<!-- TYPESCRIPT:START -->');

      const openspecContent = await readFile(openspecPath);
      expect(openspecContent).toContain('OpenSpec Instructions');
      expect(openspecContent).toContain('<!-- OPENSPEC:START -->');
    });

    it('should handle empty content', async () => {
      const emptyAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: undefined,
        blocks: [],
      };

      const result = await migrateEmbeddedTemplates(emptyAgents, config, testDir);

      expect(result.extractedLanguages).toEqual([]);
      expect(result.extractedModules).toEqual([]);
      expect(result.extractedFrameworks).toEqual([]);
    });

    it('should generate new templates when blocks not found', async () => {
      const agentsWithoutBlocks: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
        ],
      };

      const result = await migrateEmbeddedTemplates(agentsWithoutBlocks, config, testDir);

      expect(result.extractedLanguages).toContain('typescript');
      expect(result.extractedModules).toContain('openspec');

      // Verify files were created (generated, not extracted)
      const typescriptPath = path.join(testDir, 'rulebook', 'TYPESCRIPT.md');
      const openspecPath = path.join(testDir, 'rulebook', 'OPENSPEC.md');

      expect(await fileExists(typescriptPath)).toBe(true);
      expect(await fileExists(openspecPath)).toBe(true);
    });

    it('should handle custom rulebookDir', async () => {
      const customConfig: ProjectConfig = {
        ...config,
        rulebookDir: 'custom-rulebook',
      };

      await migrateEmbeddedTemplates(existingAgents, customConfig, testDir);

      const typescriptPath = path.join(testDir, 'custom-rulebook', 'TYPESCRIPT.md');
      expect(await fileExists(typescriptPath)).toBe(true);
    });

    it('should extract framework templates', async () => {
      const frameworkAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: `<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->
<!-- REACT:START -->
# React Rules
React content here.
<!-- REACT:END -->`,
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'REACT',
            startLine: 2,
            endLine: 5,
            content: '<!-- REACT:START -->\n# React Rules\nReact content here.\n<!-- REACT:END -->',
          },
        ],
      };

      const frameworkConfig: ProjectConfig = {
        ...config,
        frameworks: ['react'],
      };

      const result = await migrateEmbeddedTemplates(frameworkAgents, frameworkConfig, testDir);

      expect(result.extractedFrameworks).toContain('react');

      const reactPath = path.join(testDir, 'rulebook', 'REACT.md');
      expect(await fileExists(reactPath)).toBe(true);

      const reactContent = await readFile(reactPath);
      expect(reactContent).toContain('React Rules');
    });

    it('should handle language blocks without content', async () => {
      const agentsWithEmptyBlock: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'TYPESCRIPT',
            startLine: 2,
            endLine: 2,
            content: '', // Empty content
          },
        ],
      };

      const result = await migrateEmbeddedTemplates(agentsWithEmptyBlock, config, testDir);

      // Should generate new template when block has no content
      expect(result.extractedLanguages).toContain('typescript');
      const typescriptPath = path.join(testDir, 'rulebook', 'TYPESCRIPT.md');
      expect(await fileExists(typescriptPath)).toBe(true);
    });

    it('should handle frameworks undefined', async () => {
      const configWithoutFrameworks: ProjectConfig = {
        ...config,
        frameworks: undefined,
      };

      const result = await migrateEmbeddedTemplates(
        existingAgents,
        configWithoutFrameworks,
        testDir
      );

      expect(result.extractedFrameworks).toEqual([]);
    });

    it('should handle multiple languages and modules', async () => {
      const multiConfig: ProjectConfig = {
        languages: ['typescript', 'rust'],
        modules: ['openspec', 'vectorizer'],
        ides: ['cursor'],
        projectType: 'application',
        coverageThreshold: 95,
        strictDocs: true,
        generateWorkflows: true,
        modular: true,
      };

      const multiAgents: ExistingAgentsInfo = {
        exists: true,
        path: '',
        content: `<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->
<!-- TYPESCRIPT:START -->\nTS content\n<!-- TYPESCRIPT:END -->
<!-- RUST:START -->\nRust content\n<!-- RUST:END -->
<!-- OPENSPEC:START -->\nOpenSpec content\n<!-- OPENSPEC:END -->
<!-- VECTORIZER:START -->\nVectorizer content\n<!-- VECTORIZER:END -->`,
        blocks: [
          {
            name: 'RULEBOOK',
            startLine: 0,
            endLine: 1,
            content: '<!-- RULEBOOK:START -->\n<!-- RULEBOOK:END -->',
          },
          {
            name: 'TYPESCRIPT',
            startLine: 2,
            endLine: 4,
            content: '<!-- TYPESCRIPT:START -->\nTS content\n<!-- TYPESCRIPT:END -->',
          },
          {
            name: 'RUST',
            startLine: 5,
            endLine: 7,
            content: '<!-- RUST:START -->\nRust content\n<!-- RUST:END -->',
          },
          {
            name: 'OPENSPEC',
            startLine: 8,
            endLine: 10,
            content: '<!-- OPENSPEC:START -->\nOpenSpec content\n<!-- OPENSPEC:END -->',
          },
          {
            name: 'VECTORIZER',
            startLine: 11,
            endLine: 13,
            content: '<!-- VECTORIZER:START -->\nVectorizer content\n<!-- VECTORIZER:END -->',
          },
        ],
      };

      const result = await migrateEmbeddedTemplates(multiAgents, multiConfig, testDir);

      expect(result.extractedLanguages).toHaveLength(2);
      expect(result.extractedLanguages).toContain('typescript');
      expect(result.extractedLanguages).toContain('rust');
      expect(result.extractedModules).toHaveLength(2);
      expect(result.extractedModules).toContain('openspec');
      expect(result.extractedModules).toContain('vectorizer');
    });
  });

  describe('replaceEmbeddedWithReferences', () => {
    it('should generate modular agents content', async () => {
      const { replaceEmbeddedWithReferences } = await import('../src/core/migrator');
      const result = await replaceEmbeddedWithReferences(config, testDir);

      expect(result).toContain('<!-- RULEBOOK:START -->');
      expect(result).toContain('/rulebook/TYPESCRIPT.md');
      expect(result).toContain('/rulebook/OPENSPEC.md');
    });
  });
});
