import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { planV6Cleanup, applyV6Cleanup } from '../src/core/migration/v6-cleanup';

const OWNED = '<!-- Generated by @hivehub/rulebook — do not edit -->\n# rule body\n';

describe('v6 → v7 cleanup (migration)', () => {
    let root: string;

    beforeEach(async () => {
        root = await fs.mkdtemp(path.join(os.tmpdir(), 'rb-v6-cleanup-'));
        await fs.mkdir(path.join(root, '.claude', 'rules'), { recursive: true });
        await fs.mkdir(path.join(root, '.claude', 'hooks'), { recursive: true });
        await fs.mkdir(path.join(root, '.rulebook', 'specs'), { recursive: true });
    });

    afterEach(async () => {
        await fs.rm(root, { recursive: true, force: true });
    });

    it('removes rulebook-owned retired files but preserves user-authored ones', async () => {
        await fs.mkdir(path.join(root, '.claude', 'skills', 'rulebook-terse'), {
            recursive: true,
        });
        await fs.mkdir(path.join(root, '.rulebook', 'rules'), { recursive: true });
        await fs.mkdir(path.join(root, '.rulebook', 'handoff'), { recursive: true });
        // rulebook-owned retired rule → remove
        await fs.writeFile(path.join(root, '.claude', 'rules', 'sequential-editing.md'), OWNED);
        // same retired NAME but user-authored (no marker) → preserve
        await fs.writeFile(
            path.join(root, '.claude', 'rules', 'git-safety.md'),
            '# my own git safety notes\n'
        );
        // retired hook script → always remove
        await fs.writeFile(path.join(root, '.claude', 'hooks', 'terse-activate.sh'), '#!/bin/sh');
        // retired subsystem skill dir → remove
        await fs.writeFile(
            path.join(root, '.claude', 'skills', 'rulebook-terse', 'SKILL.md'),
            'terse'
        );
        // retired spec + canonical rule + loose files + handoff dir
        await fs.writeFile(path.join(root, '.rulebook', 'specs', 'TOKEN_OPTIMIZATION.md'), 'x');
        await fs.writeFile(path.join(root, '.rulebook', 'rules', 'no-deferred.md'), 'x');
        await fs.writeFile(path.join(root, '.rulebook', 'COMPACT_CONTEXT.md'), 'x');

        const plan = await planV6Cleanup(root);

        expect(plan.remove).toContain('.claude/rules/sequential-editing.md');
        expect(plan.preserved).toContain('.claude/rules/git-safety.md');
        expect(plan.remove).toContain('.claude/hooks/terse-activate.sh');
        expect(plan.remove).toContain('.claude/skills/rulebook-terse');
        expect(plan.remove).toContain('.rulebook/specs/TOKEN_OPTIMIZATION.md');
        expect(plan.remove).toContain('.rulebook/rules/no-deferred.md');
        expect(plan.remove).toContain('.rulebook/COMPACT_CONTEXT.md');
        expect(plan.remove).toContain('.rulebook/handoff');

        const { removed } = await applyV6Cleanup(root, plan);
        expect(removed.length).toBe(plan.remove.length);

        // preserved user file still on disk; owned one gone
        await expect(
            fs.stat(path.join(root, '.claude', 'rules', 'git-safety.md'))
        ).resolves.toBeDefined();
        await expect(
            fs.stat(path.join(root, '.claude', 'rules', 'sequential-editing.md'))
        ).rejects.toThrow();
        // emptied canonical dir dropped
        await expect(fs.stat(path.join(root, '.rulebook', 'rules'))).rejects.toThrow();
    });

    it('renames uppercase spec files to the v7 lowercase convention', async () => {
        await fs.writeFile(path.join(root, '.rulebook', 'specs', 'TYPESCRIPT.md'), '# ts spec');

        const plan = await planV6Cleanup(root);
        expect(plan.rename).toEqual([
            { from: '.rulebook/specs/TYPESCRIPT.md', to: '.rulebook/specs/typescript.md' },
        ]);

        const { renamed } = await applyV6Cleanup(root, plan);
        expect(renamed).toHaveLength(1);
        const entries = await fs.readdir(path.join(root, '.rulebook', 'specs'));
        expect(entries).toContain('typescript.md');
        expect(entries).not.toContain('TYPESCRIPT.md');
    });

    it('produces an empty plan on an already-clean v7 project', async () => {
        const plan = await planV6Cleanup(root);
        expect(plan.remove).toEqual([]);
        expect(plan.rename).toEqual([]);
        expect(plan.preserved).toEqual([]);
    });
});
