#!/bin/sh
# C# Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running C# pre-push checks..."

# Build release
echo "  → Building release..."
dotnet build -c Release || {
  echo "❌ Release build failed"
  exit 1
}

# Full test suite
echo "  → Running full test suite..."
dotnet test --no-build -c Release || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All C# pre-push checks passed!"
exit 0

