#!/bin/sh
# C# Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running C# pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.cs' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
dotnet format --verify-no-changes || {
  echo "❌ Format check failed. Run: dotnet format"
  exit 1
}

# Tests
echo "  → Running tests..."
dotnet test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All C# pre-commit checks passed!"
exit 0

