#!/bin/sh
# C# Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running C# pre-commit checks..."

# Format check
echo "  → Format checking..."
dotnet format --verify-no-changes || {
  echo "❌ Format check failed. Run: dotnet format"
  exit 1
}

# Tests
echo "  → Running tests..."
dotnet test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All C# pre-commit checks passed!"
exit 0

