#!/bin/sh
# Dart Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Dart pre-commit checks..."

# Format check
echo "  → Format checking..."
dart format --set-exit-if-changed . || {
  echo "❌ Format check failed. Run: dart format ."
  exit 1
}

# Analyze
echo "  → Analyzing..."
dart analyze --fatal-infos || {
  echo "❌ Analysis failed"
  exit 1
}

# Tests
echo "  → Running tests..."
dart test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Dart pre-commit checks passed!"
exit 0

