#!/bin/sh
# Dart Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Dart pre-push checks..."

# Full test suite with coverage
echo "  → Running tests with coverage..."
dart test --coverage=coverage || {
  echo "❌ Tests failed"
  exit 1
}

# If Flutter project
if grep -q "flutter:" pubspec.yaml 2>/dev/null; then
  echo "  → Running Flutter tests..."
  flutter test || {
    echo "❌ Flutter tests failed"
    exit 1
  }
fi

echo "✅ All Dart pre-push checks passed!"
exit 0

