#!/bin/sh
# Dart Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Dart pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.dart' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
dart format --set-exit-if-changed . || {
  echo "❌ Format check failed. Run: dart format ."
  exit 1
}

# Analyze
echo "  → Analyzing..."
dart analyze --fatal-infos || {
  echo "❌ Analysis failed"
  exit 1
}

# Tests
echo "  → Running tests..."
dart test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Dart pre-commit checks passed!"
exit 0

