#!/bin/sh
# Elixir Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Elixir pre-commit checks..."

# Format check
echo "  → Format checking..."
mix format --check-formatted || {
  echo "❌ Format check failed. Run: mix format"
  exit 1
}

# Lint
if mix help credo &> /dev/null 2>&1; then
  echo "  → Linting..."
  mix credo --strict || {
    echo "❌ Credo failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
mix test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Elixir pre-commit checks passed!"
exit 0

