#!/bin/sh
# Elixir Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Elixir pre-push checks..."

# Full test suite
echo "  → Running full test suite..."
mix test || {
  echo "❌ Tests failed"
  exit 1
}

# Compile release
echo "  → Compiling release..."
MIX_ENV=prod mix compile || {
  echo "❌ Compilation failed"
  exit 1
}

# Dialyzer (if configured)
if mix help dialyzer &> /dev/null 2>&1; then
  echo "  → Running Dialyzer..."
  mix dialyzer || {
    echo "⚠️  Dialyzer warnings found"
  }
fi

echo "✅ All Elixir pre-push checks passed!"
exit 0

