#!/bin/sh
# Elixir Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Elixir pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.ex' '*.exs' 2>/dev/null | grep "^+" | grep -cE "#[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
mix format --check-formatted || {
  echo "❌ Format check failed. Run: mix format"
  exit 1
}

# Lint
if mix help credo &> /dev/null 2>&1; then
  echo "  → Linting..."
  mix credo --strict || {
    echo "❌ Credo failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
mix test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Elixir pre-commit checks passed!"
exit 0

