#!/bin/sh
# Erlang Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Erlang pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.erl' '*.hrl' 2>/dev/null | grep "^+" | grep -cE "%[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
rebar3 format --verify || {
  echo "❌ Format check failed. Run: rebar3 format"
  exit 1
}

# Dialyzer
echo "  → Running Dialyzer..."
rebar3 dialyzer || {
  echo "❌ Dialyzer failed"
  exit 1
}

# Tests
echo "  → Running tests..."
rebar3 eunit || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Erlang pre-commit checks passed!"
exit 0

