#!/bin/sh
# Erlang Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Erlang pre-push checks..."

# Compile
echo "  → Compiling..."
rebar3 compile || {
  echo "❌ Compilation failed"
  exit 1
}

# Full test suite
echo "  → Running EUnit tests..."
rebar3 eunit || {
  echo "❌ EUnit tests failed"
  exit 1
}

echo "  → Running Common Test..."
rebar3 ct || {
  echo "❌ Common Test failed"
  exit 1
}

# Coverage (if configured)
if rebar3 help cover &> /dev/null 2>&1; then
  echo "  → Coverage check..."
  rebar3 cover || {
    echo "⚠️  Coverage check failed"
  }
fi

echo "✅ All Erlang pre-push checks passed!"
exit 0

