#!/bin/sh
# Erlang Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Erlang pre-commit checks..."

# Format check
echo "  → Format checking..."
rebar3 format --verify || {
  echo "❌ Format check failed. Run: rebar3 format"
  exit 1
}

# Dialyzer
echo "  → Running Dialyzer..."
rebar3 dialyzer || {
  echo "❌ Dialyzer failed"
  exit 1
}

# Tests
echo "  → Running tests..."
rebar3 eunit || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Erlang pre-commit checks passed!"
exit 0

