#!/bin/sh
# Go Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Go pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.go' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
  echo "❌ Go files not formatted. Run: gofmt -w ."
  gofmt -l .
  exit 1
fi

# Vet
echo "  → Running go vet..."
go vet ./... || {
  echo "❌ go vet failed"
  exit 1
}

# Lint (if golangci-lint available)
if command -v golangci-lint &> /dev/null; then
  echo "  → Linting..."
  golangci-lint run || {
    echo "❌ Linting failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
go test ./... || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Go pre-commit checks passed!"
exit 0

