#!/bin/sh
# Go Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Go pre-commit checks..."

# Format check
echo "  → Format checking..."
if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
  echo "❌ Go files not formatted. Run: gofmt -w ."
  gofmt -l .
  exit 1
fi

# Vet
echo "  → Running go vet..."
go vet ./... || {
  echo "❌ go vet failed"
  exit 1
}

# Lint (if golangci-lint available)
if command -v golangci-lint &> /dev/null; then
  echo "  → Linting..."
  golangci-lint run || {
    echo "❌ Linting failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
go test ./... || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Go pre-commit checks passed!"
exit 0

