#!/bin/sh
# Go Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Go pre-push checks..."

# Full test suite with coverage
echo "  → Running tests with coverage..."
go test -cover ./... || {
  echo "❌ Tests failed"
  exit 1
}

# Build
echo "  → Building..."
go build ./... || {
  echo "❌ Build failed"
  exit 1
}

# Security check (if gosec available)
if command -v gosec &> /dev/null; then
  echo "  → Security scan..."
  gosec ./... || {
    echo "⚠️  Security issues found"
  }
fi

echo "✅ All Go pre-push checks passed!"
exit 0

