#!/bin/sh
# Haskell Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Haskell pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.hs' 2>/dev/null | grep "^+" | grep -cE "--[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Lint
if command -v hlint &> /dev/null; then
  echo "  → Linting..."
  hlint . || {
    echo "❌ HLint failed"
    exit 1
  }
fi

# Format check (if ormolu available)
if command -v ormolu &> /dev/null; then
  echo "  → Format checking..."
  ormolu --mode check $(find . -name '*.hs') || {
    echo "❌ Format check failed. Run: ormolu --mode inplace \$(find . -name '*.hs')"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
if [ -f "stack.yaml" ]; then
  stack test || {
    echo "❌ Tests failed"
    exit 1
  }
else
  cabal test || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All Haskell pre-commit checks passed!"
exit 0

