#!/bin/sh
# Haskell Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Haskell pre-push checks..."

# Build
echo "  → Building..."
if [ -f "stack.yaml" ]; then
  stack build || {
    echo "❌ Build failed"
    exit 1
  }
  
  # Full tests
  echo "  → Running full test suite..."
  stack test || {
    echo "❌ Tests failed"
    exit 1
  }
else
  cabal build || {
    echo "❌ Build failed"
    exit 1
  }
  
  # Full tests
  echo "  → Running full test suite..."
  cabal test || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All Haskell pre-push checks passed!"
exit 0

