#!/bin/sh
# Java Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Java pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.java' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


if [ -f "pom.xml" ]; then
  echo "  → Maven checks..."
  
  # Format check
  mvn spotless:check || {
    echo "❌ Format check failed. Run: mvn spotless:apply"
    exit 1
  }
  
  # Verify
  mvn verify || {
    echo "❌ Maven verify failed"
    exit 1
  }
  
elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
  echo "  → Gradle checks..."
  
  # Check
  ./gradlew check || {
    echo "❌ Gradle check failed"
    exit 1
  }
fi

echo "✅ All Java pre-commit checks passed!"
exit 0

