#!/bin/sh
# Java Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Java pre-push checks..."

if [ -f "pom.xml" ]; then
  echo "  → Maven clean package..."
  mvn clean package || {
    echo "❌ Maven package failed"
    exit 1
  }
  
elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
  echo "  → Gradle clean build..."
  ./gradlew clean build || {
    echo "❌ Gradle build failed"
    exit 1
  }
fi

echo "✅ All Java pre-push checks passed!"
exit 0

