#!/bin/sh
# Java Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Java pre-commit checks..."

if [ -f "pom.xml" ]; then
  echo "  → Maven checks..."
  
  # Format check
  mvn spotless:check || {
    echo "❌ Format check failed. Run: mvn spotless:apply"
    exit 1
  }
  
  # Verify
  mvn verify || {
    echo "❌ Maven verify failed"
    exit 1
  }
  
elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
  echo "  → Gradle checks..."
  
  # Check
  ./gradlew check || {
    echo "❌ Gradle check failed"
    exit 1
  }
fi

echo "✅ All Java pre-commit checks passed!"
exit 0

