#!/bin/sh
# Kotlin Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Kotlin pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.kt' '*.kts' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Lint
echo "  → Linting..."
./gradlew ktlintCheck || {
  echo "❌ ktlint failed. Run: ./gradlew ktlintFormat"
  exit 1
}

# Detekt
if ./gradlew tasks --all | grep -q detekt; then
  echo "  → Running Detekt..."
  ./gradlew detekt || {
    echo "❌ Detekt failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
./gradlew test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Kotlin pre-commit checks passed!"
exit 0

