#!/bin/sh
# Kotlin Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Kotlin pre-push checks..."

# Clean build
echo "  → Clean building..."
./gradlew clean build || {
  echo "❌ Build failed"
  exit 1
}

echo "✅ All Kotlin pre-push checks passed!"
exit 0

