#!/bin/sh
# Kotlin Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Kotlin pre-commit checks..."

# Lint
echo "  → Linting..."
./gradlew ktlintCheck || {
  echo "❌ ktlint failed. Run: ./gradlew ktlintFormat"
  exit 1
}

# Detekt
if ./gradlew tasks --all | grep -q detekt; then
  echo "  → Running Detekt..."
  ./gradlew detekt || {
    echo "❌ Detekt failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
./gradlew test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Kotlin pre-commit checks passed!"
exit 0

