#!/bin/sh
# PHP Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running PHP pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.php' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format & Lint
if command -v php-cs-fixer &> /dev/null; then
  echo "  → Format checking..."
  php-cs-fixer fix --dry-run --diff || {
    echo "❌ Format check failed. Run: php-cs-fixer fix"
    exit 1
  }
fi

# Static analysis
if command -v phpstan &> /dev/null; then
  echo "  → Static analysis..."
  phpstan analyze || {
    echo "❌ PHPStan failed"
    exit 1
  }
fi

# Tests
if command -v phpunit &> /dev/null; then
  echo "  → Running tests..."
  phpunit || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All PHP pre-commit checks passed!"
exit 0

