#!/bin/sh
# PHP Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running PHP pre-push checks..."

# Full test suite
if command -v phpunit &> /dev/null; then
  echo "  → Running full test suite..."
  phpunit --coverage-text || {
    echo "❌ Tests or coverage failed"
    exit 1
  }
fi

# Security check
if command -v composer &> /dev/null; then
  echo "  → Security audit..."
  composer audit || {
    echo "⚠️  Security vulnerabilities found"
  }
fi

echo "✅ All PHP pre-push checks passed!"
exit 0

