#!/bin/sh
# PHP Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running PHP pre-commit checks..."

# Format & Lint
if command -v php-cs-fixer &> /dev/null; then
  echo "  → Format checking..."
  php-cs-fixer fix --dry-run --diff || {
    echo "❌ Format check failed. Run: php-cs-fixer fix"
    exit 1
  }
fi

# Static analysis
if command -v phpstan &> /dev/null; then
  echo "  → Static analysis..."
  phpstan analyze || {
    echo "❌ PHPStan failed"
    exit 1
  }
fi

# Tests
if command -v phpunit &> /dev/null; then
  echo "  → Running tests..."
  phpunit || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All PHP pre-commit checks passed!"
exit 0

