#!/bin/sh
# Python Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Python pre-commit checks..."

# Format check
if command -v black &> /dev/null; then
  echo "  → Format checking..."
  black --check . || {
    echo "❌ Format check failed. Run: black ."
    exit 1
  }
fi

# Lint
if command -v ruff &> /dev/null; then
  echo "  → Linting with Ruff..."
  ruff check . || {
    echo "❌ Ruff check failed"
    exit 1
  }
elif command -v flake8 &> /dev/null; then
  echo "  → Linting with Flake8..."
  flake8 . || {
    echo "❌ Flake8 check failed"
    exit 1
  }
fi

# Type check
if command -v mypy &> /dev/null; then
  echo "  → Type checking..."
  mypy . || {
    echo "❌ Type check failed"
    exit 1
  }
fi

# Tests
if command -v pytest &> /dev/null; then
  echo "  → Running tests..."
  pytest || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All Python pre-commit checks passed!"
exit 0

