#!/bin/sh
# Python Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Python pre-push checks..."

# Full test suite with coverage
if command -v pytest &> /dev/null; then
  echo "  → Running full test suite with coverage..."
  pytest --cov --cov-report=term-missing || {
    echo "❌ Tests or coverage failed"
    exit 1
  }
fi

# Security audit
if [ -f "requirements.txt" ] && command -v pip-audit &> /dev/null; then
  echo "  → Security audit..."
  pip-audit || {
    echo "⚠️  Security vulnerabilities found"
  }
fi

echo "✅ All Python pre-push checks passed!"
exit 0
