#!/bin/sh
# Ruby Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Ruby pre-push checks..."

# Full test suite
if command -v rspec &> /dev/null; then
  echo "  → Running full test suite..."
  bundle exec rspec || {
    echo "❌ Tests failed"
    exit 1
  }
elif command -v rake &> /dev/null; then
  echo "  → Running tests..."
  bundle exec rake test || {
    echo "❌ Tests failed"
    exit 1
  }
fi

# Security audit
if command -v bundler-audit &> /dev/null; then
  echo "  → Security audit..."
  bundle exec bundler-audit check --update || {
    echo "⚠️  Security vulnerabilities found"
  }
fi

echo "✅ All Ruby pre-push checks passed!"
exit 0

