#!/bin/sh
# Ruby Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Ruby pre-commit checks..."

# Lint
if command -v rubocop &> /dev/null; then
  echo "  → Linting..."
  rubocop || {
    echo "❌ RuboCop failed"
    exit 1
  }
fi

# Tests
if command -v rspec &> /dev/null; then
  echo "  → Running tests..."
  bundle exec rspec || {
    echo "❌ Tests failed"
    exit 1
  }
elif command -v rake &> /dev/null; then
  echo "  → Running tests..."
  bundle exec rake test || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All Ruby pre-commit checks passed!"
exit 0

