#!/bin/sh
# Ruby Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Ruby pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.rb' 2>/dev/null | grep "^+" | grep -cE "#[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Lint
if command -v rubocop &> /dev/null; then
  echo "  → Linting..."
  rubocop || {
    echo "❌ RuboCop failed"
    exit 1
  }
fi

# Tests
if command -v rspec &> /dev/null; then
  echo "  → Running tests..."
  bundle exec rspec || {
    echo "❌ Tests failed"
    exit 1
  }
elif command -v rake &> /dev/null; then
  echo "  → Running tests..."
  bundle exec rake test || {
    echo "❌ Tests failed"
    exit 1
  }
fi

echo "✅ All Ruby pre-commit checks passed!"
exit 0

