#!/bin/sh
# Rust Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Rust pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.rs' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
cargo fmt --all -- --check || {
  echo "❌ Format check failed. Run: cargo fmt"
  exit 1
}

# Clippy
echo "  → Running Clippy..."
cargo clippy --all-targets --all-features -- -D warnings || {
  echo "❌ Clippy failed"
  exit 1
}

# Tests
echo "  → Running tests..."
cargo test --all-features || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Rust pre-commit checks passed!"
exit 0

