#!/bin/sh
# Rust Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Rust pre-commit checks..."

# Format check
echo "  → Format checking..."
cargo fmt --all -- --check || {
  echo "❌ Format check failed. Run: cargo fmt"
  exit 1
}

# Clippy
echo "  → Running Clippy..."
cargo clippy --all-targets --all-features -- -D warnings || {
  echo "❌ Clippy failed"
  exit 1
}

# Tests
echo "  → Running tests..."
cargo test --all-features || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Rust pre-commit checks passed!"
exit 0

