#!/bin/sh
# Rust Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Rust pre-push checks..."

# Full test suite
echo "  → Running full test suite..."
cargo test --all-features || {
  echo "❌ Tests failed"
  exit 1
}

# Build release
echo "  → Building release..."
cargo build --release || {
  echo "❌ Release build failed"
  exit 1
}

# Check
echo "  → Running cargo check..."
cargo check --all-targets --all-features || {
  echo "❌ Cargo check failed"
  exit 1
}

echo "✅ All Rust pre-push checks passed!"
exit 0

