#!/bin/sh
# Scala Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Scala pre-commit checks..."

# Format check
echo "  → Format checking..."
sbt scalafmtCheckAll || {
  echo "❌ Format check failed. Run: sbt scalafmtAll"
  exit 1
}

# Lint (if scalafix configured)
if sbt tasks | grep -q scalafix; then
  echo "  → Linting..."
  sbt "scalafix --check" || {
    echo "❌ Scalafix failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
sbt test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Scala pre-commit checks passed!"
exit 0

