#!/bin/sh
# Scala Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Scala pre-push checks..."

# Clean compile
echo "  → Clean compiling..."
sbt clean compile test || {
  echo "❌ Build or tests failed"
  exit 1
}

# Coverage (if configured)
if sbt tasks | grep -q coverage; then
  echo "  → Coverage check..."
  sbt coverage test coverageReport || {
    echo "⚠️  Coverage check failed"
  }
fi

echo "✅ All Scala pre-push checks passed!"
exit 0

