#!/bin/sh
# Scala Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Scala pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.scala' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Format check
echo "  → Format checking..."
sbt scalafmtCheckAll || {
  echo "❌ Format check failed. Run: sbt scalafmtAll"
  exit 1
}

# Lint (if scalafix configured)
if sbt tasks | grep -q scalafix; then
  echo "  → Linting..."
  sbt "scalafix --check" || {
    echo "❌ Scalafix failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
sbt test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Scala pre-commit checks passed!"
exit 0

