#!/bin/sh
# Swift Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Swift pre-commit checks..."

# Lint
if command -v swiftlint &> /dev/null; then
  echo "  → Linting..."
  swiftlint || {
    echo "❌ SwiftLint failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
swift test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Swift pre-commit checks passed!"
exit 0

