#!/bin/sh
# Swift Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running Swift pre-push checks..."

# Build release
echo "  → Building release..."
swift build -c release || {
  echo "❌ Release build failed"
  exit 1
}

# Full test suite
echo "  → Running full test suite..."
swift test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Swift pre-push checks passed!"
exit 0

