#!/bin/sh
# Swift Pre-Commit Hook
# Generated by @hivellm/rulebook

echo "🔍 Running Swift pre-commit checks..."

# Marker-comment gate (v7 — replaces the old PreToolUse content regex).
# Only lines ADDED by this commit are checked, so existing occurrences
# and legitimate strings elsewhere never trip it.
markers=$(git diff --cached --unified=0 -- '*.swift' 2>/dev/null | grep "^+" | grep -cE "//[[:space:]]*(TODO|FIXME|HACK)\\b" || true)
if [ "${markers:-0}" -gt 0 ]; then
  echo "❌ Staged changes add $markers TODO/FIXME/HACK marker comment(s). Implement or remove them before committing."
  exit 1
fi


# Lint
if command -v swiftlint &> /dev/null; then
  echo "  → Linting..."
  swiftlint || {
    echo "❌ SwiftLint failed"
    exit 1
  }
fi

# Tests
echo "  → Running tests..."
swift test || {
  echo "❌ Tests failed"
  exit 1
}

echo "✅ All Swift pre-commit checks passed!"
exit 0

