#!/bin/sh
# TypeScript/JavaScript Pre-Commit Hook
# Generated by @hivellm/rulebook
# Fast checks only: formatting, linting, type-check (no tests for backup commits)

echo "🔍 Running TypeScript/JavaScript pre-commit checks..."

# Format check
if command -v prettier &> /dev/null; then
  echo "  → Format checking..."
  npx prettier --check "src/**/*.{ts,tsx,js,jsx}" "tests/**/*.{ts,tsx,js,jsx}" 2>/dev/null || {
    echo "❌ Format check failed. Run: npm run format"
    exit 1
  }
fi

# Lint
if grep -q '"lint"' package.json 2>/dev/null; then
  echo "  → Linting..."
  npm run lint || {
    echo "❌ Linting failed"
    exit 1
  }
fi

# Type check
if grep -q '"type-check"' package.json 2>/dev/null; then
  echo "  → Type checking..."
  npm run type-check || {
    echo "❌ Type check failed"
    exit 1
  }
fi

echo "✅ All TypeScript/JavaScript pre-commit checks passed!"
exit 0

