#!/bin/sh
# TypeScript/JavaScript Pre-Push Hook
# Generated by @hivellm/rulebook

echo "🚀 Running TypeScript/JavaScript pre-push checks..."

# Build (MANDATORY before push)
if grep -q '"build"' package.json 2>/dev/null; then
  echo "  → Building..."
  npm run build || {
    echo "❌ Build failed"
    exit 1
  }
fi

# Full test suite
if grep -q '"test"' package.json 2>/dev/null; then
  echo "  → Running full test suite..."
  npm test || {
    echo "❌ Tests failed"
    exit 1
  }
fi

# Coverage check
if grep -q '"test:coverage"' package.json 2>/dev/null; then
  echo "  → Checking coverage..."
  npm run test:coverage || {
    echo "❌ Coverage check failed"
    exit 1
  }
fi

echo "✅ All TypeScript/JavaScript pre-push checks passed!"
exit 0

