name: Go Lint

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
    
    - name: Check formatting
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Run: gofmt -w ."
          gofmt -l .
          exit 1
        fi
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
    
    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run --timeout=5m

