name: Kotlin Lint

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run ktlint
      run: ./gradlew ktlintCheck
    
    - name: Run Detekt
      run: ./gradlew detekt
    
    - name: Build with warnings as errors
      run: ./gradlew build -x test

