name: PHP Lint

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl
    
    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHP-CS-Fixer
      run: composer cs-check
    
    - name: Run PHPStan
      run: composer stan
    
    - name: Run PHPCS
      run: composer phpcs

