name: Solidity Lint

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    # IMPORTANT: For cache to work, you MUST commit package-lock.json
    # Remove package-lock.json from .gitignore if needed
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check code formatting
      run: npx prettier --check 'contracts/**/*.sol' 'test/**/*.js'
      # or: forge fmt --check (for Foundry)
    
    - name: Run Solhint
      run: npx solhint 'contracts/**/*.sol'
    
    - name: Run Slither security analysis
      uses: crytic/slither-action@v0.3.0
      with:
        target: '.'
        fail-on: medium


