name: Swift Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        swift-version: [ '5.10' ]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v --enable-code-coverage
    
    - name: Generate coverage report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/YourPackagePackageTests.xctest/Contents/MacOS/YourPackagePackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.lcov
        flags: unittests
        fail_ci_if_error: false

