name: Zig Lint

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: '0.13.0'
    
    - name: Check formatting
      run: zig fmt --check src/ tests/
    
    - name: Build check
      run: zig build -Doptimize=ReleaseFast


