import path from 'path';
import { readFile, writeFile, fileExists, ensureDir } from '../utils/file-system.js';
import type { DetectionResult } from '../types.js';
import { getTemplatesDir } from './generator.js';

/**
 * v5.3.0 `.claude/rules/` generator.
 *
 * For every detected language that rulebook ships a template for, emit
 * `.claude/rules/<language>.md` with YAML `paths:` frontmatter. These are
 * Anthropic's path-scoped rules (loaded only when Claude reads a file
 * matching the glob), so they cost zero context budget outside of the
 * relevant file types.
 *
 * Files generated by rulebook carry a sentinel comment immediately after
 * the frontmatter. On `rulebook update`, any `.claude/rules/*.md` without
 * the sentinel is treated as user-authored and left alone. This lets users
 * adopt a generated rule file as their own by simply deleting the sentinel
 * comment line.
 */

export const RULES_DIR = '.claude/rules';
export const GENERATED_SENTINEL = 'Generated by @hivehub/rulebook v5.3.0';

/**
 * Languages with shipped rule templates. Adding a new entry here requires a
 * matching `templates/rules/<slug>.md` file.
 */
export const SUPPORTED_RULE_LANGUAGES = [
  'typescript',
  'javascript',
  'rust',
  'python',
  'go',
  'cpp',
  'java',
  'csharp',
] as const;

/**
 * Generic (non-language) rules shipped by rulebook v5.3.0.
 * These are always emitted regardless of detection result.
 */
export const ALWAYS_ON_RULES = [
  'full-task-no-questions',
  'multi-agent-teams',
  'consult-analysis-before-implementing',
  'respect-handoff-trigger',
  'diagnostic-first',
] as const;

export type SupportedRuleLanguage = (typeof SUPPORTED_RULE_LANGUAGES)[number];

/**
 * Detected languages from the `detector.ts` pipeline may use aliases
 * (e.g. `"c"` — which rulebook treats as C/C++ and routes to the `cpp`
 * template). Map them here.
 */
const LANGUAGE_ALIASES: Record<string, SupportedRuleLanguage> = {
  c: 'cpp',
  'c++': 'cpp',
  cs: 'csharp',
  'c#': 'csharp',
  ts: 'typescript',
  js: 'javascript',
  py: 'python',
  rs: 'rust',
};

export interface RulesGenerationResult {
  /** Paths of rule files written (new or overwritten). */
  written: string[];
  /** Paths of rule files skipped because they lack the generated sentinel. */
  preserved: string[];
  /** Languages detected but not shipped as rule templates. */
  unsupported: string[];
}

export function getRulesDir(projectRoot: string): string {
  return path.join(projectRoot, RULES_DIR);
}

export function getRulePath(projectRoot: string, language: SupportedRuleLanguage): string {
  return path.join(getRulesDir(projectRoot), `${language}.md`);
}

/**
 * Normalize a detected language string to a supported rule template slug.
 * Returns null if rulebook does not ship a template for it.
 */
export function resolveRuleLanguage(detected: string): SupportedRuleLanguage | null {
  const lower = detected.toLowerCase().trim();
  if (SUPPORTED_RULE_LANGUAGES.includes(lower as SupportedRuleLanguage)) {
    return lower as SupportedRuleLanguage;
  }
  return LANGUAGE_ALIASES[lower] ?? null;
}

/**
 * Read a language rule template from the package's `templates/rules/`
 * directory.
 */
export async function readRuleTemplate(language: SupportedRuleLanguage): Promise<string> {
  const templatePath = path.join(getTemplatesDir(), 'rules', `${language}.md`);
  if (!(await fileExists(templatePath))) {
    throw new Error(`Rule template not found at ${templatePath}`);
  }
  return await readFile(templatePath);
}

/**
 * Check whether an existing rule file was generated by rulebook. Returns
 * true only if the canonical sentinel comment is present. User files that
 * the user "adopted" by deleting the sentinel return false and are
 * preserved across updates.
 */
export function hasGeneratedSentinel(content: string): boolean {
  return content.includes(GENERATED_SENTINEL);
}

/**
 * Generate `.claude/rules/<language>.md` for every detected language that
 * has a shipped template. User-authored rules (no sentinel) are preserved.
 */
export async function generateRules(
  projectRoot: string,
  detection: Pick<DetectionResult, 'languages'>
): Promise<RulesGenerationResult> {
  const rulesDir = getRulesDir(projectRoot);
  await ensureDir(rulesDir);

  const result: RulesGenerationResult = {
    written: [],
    preserved: [],
    unsupported: [],
  };

  // Deduplicate: a project might detect both "typescript" and "javascript";
  // we emit both rules since both apply. But if two detection entries map
  // to the same template slug, only write once.
  const seen = new Set<SupportedRuleLanguage>();

  for (const entry of detection.languages) {
    const slug = resolveRuleLanguage(entry.language);
    if (!slug) {
      result.unsupported.push(entry.language);
      continue;
    }
    if (seen.has(slug)) continue;
    seen.add(slug);

    const targetPath = getRulePath(projectRoot, slug);

    if (await fileExists(targetPath)) {
      const existing = await readFile(targetPath);
      if (!hasGeneratedSentinel(existing)) {
        // User-owned file — never touch it.
        result.preserved.push(targetPath);
        continue;
      }
    }

    const template = await readRuleTemplate(slug);
    await writeFile(targetPath, template);
    result.written.push(targetPath);
  }

  // Always-on rules (not language-scoped) — emit if sentinel-based skip allows
  for (const ruleName of ALWAYS_ON_RULES) {
    const targetPath = path.join(rulesDir, `${ruleName}.md`);
    if (await fileExists(targetPath)) {
      const existing = await readFile(targetPath);
      if (!hasGeneratedSentinel(existing)) {
        result.preserved.push(targetPath);
        continue;
      }
    }
    const templatePath = path.join(getTemplatesDir(), 'rules', `${ruleName}.md`);
    if (await fileExists(templatePath)) {
      const template = await readFile(templatePath);
      await writeFile(targetPath, template);
      result.written.push(targetPath);
    }
  }

  return result;
}

/**
 * List all rule files currently present in `.claude/rules/`, classifying
 * each by origin (generated by rulebook vs user-authored).
 */
export interface ListedRule {
  name: string;
  path: string;
  source: 'generated' | 'user';
  paths: string[] | null;
}

export async function listRulesWithSource(projectRoot: string): Promise<ListedRule[]> {
  const rulesDir = getRulesDir(projectRoot);
  if (!(await fileExists(rulesDir))) return [];

  const { promises: fs } = await import('fs');
  const entries = await fs.readdir(rulesDir, { withFileTypes: true });
  const results: ListedRule[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const filePath = path.join(rulesDir, entry.name);
    const content = await readFile(filePath);
    const source: ListedRule['source'] = hasGeneratedSentinel(content) ? 'generated' : 'user';
    results.push({
      name: entry.name.replace(/\.md$/, ''),
      path: filePath,
      source,
      paths: extractPathsFrontmatter(content),
    });
  }

  results.sort((a, b) => a.name.localeCompare(b.name));
  return results;
}

/**
 * Extract the `paths:` field from a YAML frontmatter block at the top of a
 * markdown file. Returns null if no frontmatter or no `paths:` field.
 * Intentionally simple — handles the exact shape the shipped templates use,
 * not arbitrary YAML. Callers that need full YAML support should use a real
 * parser.
 */
function extractPathsFrontmatter(content: string): string[] | null {
  // Handle both LF and CRLF line endings (Windows writes CRLF)
  const normalized = content.replace(/\r\n/g, '\n');
  const match = normalized.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const frontmatter = match[1];
  const pathsMatch = frontmatter.match(/^paths:\s*\n((?:\s*-\s+.+\n?)+)/m);
  if (!pathsMatch) return null;
  const lines = pathsMatch[1].split('\n').filter((l) => l.trim().startsWith('-'));
  return lines.map((l) =>
    l
      .replace(/^\s*-\s+/, '')
      .replace(/^["']|["']$/g, '')
      .trim()
  );
}
