import path from 'path';
import { writeFile, fileExists, readFile, ensureDir } from '../utils/file-system.js';

/**
 * v5.3.0 F3 — `.rulebook/STATE.md` auto-regeneration.
 *
 * Renders a short (<40 line) machine-written status file imported by
 * CLAUDE.md via `@.rulebook/STATE.md`. Updated on every task state
 * change or Ralph iteration. Users can opt out by adding a
 * `manual: true` YAML frontmatter flag.
 */

export const STATE_FILE = '.rulebook/STATE.md';

export interface StateSnapshot {
  activeTask?: { id: string; phase: string; progress: string } | null;
  lastRalphIteration?: number | null;
  lastQualityGate?: string | null;
  healthScore?: number | null;
  updatedAt: string;
}

export function getStatePath(projectRoot: string): string {
  return path.join(projectRoot, STATE_FILE);
}

/**
 * Check whether the STATE.md has `manual: true` frontmatter, meaning
 * the user maintains it by hand and rulebook should not touch it.
 */
export async function isManuallyMaintained(projectRoot: string): Promise<boolean> {
  const target = getStatePath(projectRoot);
  if (!(await fileExists(target))) return false;
  const content = await readFile(target);
  return /^---\n[\s\S]*?manual:\s*true/m.test(content);
}

/**
 * Write or overwrite `.rulebook/STATE.md` with the given snapshot.
 * No-op if the file has `manual: true` frontmatter.
 */
export async function writeState(
  projectRoot: string,
  snapshot: StateSnapshot
): Promise<{ path: string; written: boolean }> {
  if (await isManuallyMaintained(projectRoot)) {
    return { path: getStatePath(projectRoot), written: false };
  }

  const target = getStatePath(projectRoot);
  await ensureDir(path.dirname(target));
  const content = renderState(snapshot);
  await writeFile(target, content);
  return { path: target, written: true };
}

function renderState(s: StateSnapshot): string {
  const lines: string[] = [
    '<!-- Auto-generated by rulebook v5.3.0. Do not edit — changes will be overwritten. -->',
    '<!-- Add `manual: true` frontmatter to opt out of auto-generation. -->',
    '',
    '# Project state',
    '',
    `**Last updated**: ${s.updatedAt}`,
    '',
  ];

  if (s.activeTask) {
    lines.push(`## Active task`);
    lines.push('');
    lines.push(`- **ID**: \`${s.activeTask.id}\``);
    lines.push(`- **Phase**: ${s.activeTask.phase}`);
    lines.push(`- **Progress**: ${s.activeTask.progress}`);
    lines.push('');
  } else {
    lines.push('## Active task');
    lines.push('');
    lines.push('No active task.');
    lines.push('');
  }

  if (s.lastRalphIteration != null) {
    lines.push(`## Ralph`);
    lines.push('');
    lines.push(`- **Last iteration**: ${s.lastRalphIteration}`);
    if (s.lastQualityGate) {
      lines.push(`- **Quality gate**: ${s.lastQualityGate}`);
    }
    lines.push('');
  }

  if (s.healthScore != null) {
    lines.push(`## Health`);
    lines.push('');
    lines.push(`- **Score**: ${s.healthScore}/100`);
    lines.push('');
  }

  return lines.join('\n');
}
