#!/usr/bin/env node
/**
 * Fan out the `rulebook-terse` skill family to agent-specific rule
 * locations inside this repo.
 *
 * Source of truth:
 *   - `templates/skills/core/rulebook-terse/SKILL.md`
 *   - `templates/skills/core/rulebook-terse-commit/SKILL.md`
 *   - `templates/skills/core/rulebook-terse-review/SKILL.md`
 *
 * Projections (overwritten on every sync — do-not-edit):
 *   - .claude/skills/rulebook-terse.../SKILL.md
 *   - .cursor/rules/rulebook-terse.mdc     (alwaysApply: true frontmatter)
 *   - .windsurf/rules/rulebook-terse.md    (trigger: always_on frontmatter)
 *   - .clinerules/rulebook-terse.md        (no frontmatter)
 *   - .codex/rulebook-terse.md             (no frontmatter)
 *
 * CI workflow `.github/workflows/sync-agent-rules.yml` invokes this on
 * every push to `main` that touches the source SKILL.md files, and
 * commits back with `[skip ci]`.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface Projection {
  /** Relative destination path from repo root. */
  dest: string;
  /** Optional prepended frontmatter (newline-terminated). */
  frontmatter?: string;
  /** Whether the destination is a directory of SKILL.md (Claude Code) vs a single rule file. */
  asSkillDir?: boolean;
}

const SOURCE_SKILLS = [
  'rulebook-terse',
  'rulebook-terse-commit',
  'rulebook-terse-review',
] as const;

const DO_NOT_EDIT_BANNER =
  '<!-- AUTO-GENERATED by scripts/sync-agent-rules.ts — do not edit. Source: templates/skills/core/<name>/SKILL.md -->\n';

const PROJECTIONS_FOR: Record<(typeof SOURCE_SKILLS)[number], Projection[]> = {
  'rulebook-terse': [
    { dest: '.claude/skills/rulebook-terse/SKILL.md', asSkillDir: true },
    {
      dest: '.cursor/rules/rulebook-terse.mdc',
      frontmatter: '---\nalwaysApply: true\n---\n',
    },
    {
      dest: '.windsurf/rules/rulebook-terse.md',
      frontmatter: '---\ntrigger: always_on\n---\n',
    },
    { dest: '.clinerules/rulebook-terse.md' },
    { dest: '.codex/rulebook-terse.md' },
  ],
  'rulebook-terse-commit': [
    { dest: '.claude/skills/rulebook-terse-commit/SKILL.md', asSkillDir: true },
    {
      dest: '.cursor/rules/rulebook-terse-commit.mdc',
      frontmatter: '---\nalwaysApply: false\n---\n',
    },
    {
      dest: '.windsurf/rules/rulebook-terse-commit.md',
      frontmatter: '---\ntrigger: manual\n---\n',
    },
    { dest: '.clinerules/rulebook-terse-commit.md' },
    { dest: '.codex/rulebook-terse-commit.md' },
  ],
  'rulebook-terse-review': [
    { dest: '.claude/skills/rulebook-terse-review/SKILL.md', asSkillDir: true },
    {
      dest: '.cursor/rules/rulebook-terse-review.mdc',
      frontmatter: '---\nalwaysApply: false\n---\n',
    },
    {
      dest: '.windsurf/rules/rulebook-terse-review.md',
      frontmatter: '---\ntrigger: manual\n---\n',
    },
    { dest: '.clinerules/rulebook-terse-review.md' },
    { dest: '.codex/rulebook-terse-review.md' },
  ],
};

function stripSourceFrontmatter(body: string): string {
  // Source SKILL.md uses Rulebook's own YAML frontmatter (name, version,
  // etc.). Downstream rule files don't need it — strip and keep the body.
  const match = body.match(/^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)$/);
  return match ? match[1] : body;
}

export function buildProjectionContent(
  sourceBody: string,
  frontmatter: string | undefined,
  includeBanner: boolean
): string {
  const body = stripSourceFrontmatter(sourceBody);
  const banner = includeBanner ? DO_NOT_EDIT_BANNER : '';
  return `${frontmatter ?? ''}${banner}${body}`;
}

export function syncAgentRules(repoRoot: string): { written: string[]; skipped: string[] } {
  const written: string[] = [];
  const skipped: string[] = [];

  for (const skillName of SOURCE_SKILLS) {
    const sourcePath = resolve(
      repoRoot,
      'templates',
      'skills',
      'core',
      skillName,
      'SKILL.md'
    );
    if (!existsSync(sourcePath)) {
      skipped.push(sourcePath);
      continue;
    }
    const sourceBody = readFileSync(sourcePath, 'utf8');

    for (const projection of PROJECTIONS_FOR[skillName]) {
      const abs = resolve(repoRoot, projection.dest);
      mkdirSync(dirname(abs), { recursive: true });

      // Claude Code skill directories preserve the full SKILL.md
      // (including original frontmatter) so the local plugin engine
      // can parse it normally. The agent-specific rule files, by
      // contrast, get the body only with platform-specific
      // frontmatter attached.
      const content = projection.asSkillDir
        ? sourceBody
        : buildProjectionContent(sourceBody, projection.frontmatter, true);

      writeFileSync(abs, content);
      written.push(projection.dest);
    }
  }

  return { written, skipped };
}

const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === __filename) {
  const root = process.cwd();
  const { written, skipped } = syncAgentRules(root);
  for (const f of written) console.log(`wrote  ${f}`);
  for (const f of skipped) console.log(`skipped (source missing): ${f}`);
  process.exit(skipped.length === 0 ? 0 : 1);
}
